/**
 * Generate Selector route — POST /profile-tooling/generate-selector
 *
 * Accepts a pasted element's outerHTML plus the full page HTML and
 * returns a stable CSS selector generated from the shared
 * `buildStableSelector` function.
 *
 * This enables the "paste-element-to-selector" flow (Layer 2) where a
 * user copies an element from DevTools and gets a stable selector
 * generated by the same algorithm the LLM-based profile generation
 * uses, but sourced from a real element rather than an LLM guess.
 */

import type { IncomingMessage, ServerResponse } from 'node:http';
import * as cheerio from 'cheerio';
import {
  GenerateSelectorRequestSchema,
  GenerateSelectorResponseSchema,
} from '../../shared/schemas/extraction-worker';
import type { GenerateSelectorResponse } from '../../shared/schemas/extraction-worker';
import {
  buildStableSelector,
  isSupportedSelectorSyntax,
} from '../../shared/selector-utils';

// ─── Image source helpers (inlined — worker cannot import Bun-only modules) ──

/**
 * Returns true when a source URL is usable as a product image —
 * non-empty, not a data URI, not a blob URI, and not an SVG.
 */
function isUsableImageSource(src: string | null | undefined): src is string {
  if (!src) return false;
  const trimmed = src.trim();
  if (!trimmed) return false;
  if (trimmed.startsWith('data:')) return false;
  if (trimmed.startsWith('blob:')) return false;
  if (trimmed.endsWith('.svg')) return false;
  return true;
}

/**
 * Collect image source URLs from a Cheerio element and its descendants.
 */
function collectImageSourcesFromElement(
  $: cheerio.CheerioAPI,
  el: cheerio.Element,
): string[] {
  const sources: string[] = [];
  const node = $(el);

  // Check the element itself first (for <img> elements).
  if (el.tagName?.toLowerCase() === 'img') {
    const src = node.attr('src');
    if (isUsableImageSource(src)) sources.push(src);
    const dataSrc = node.attr('data-src');
    if (isUsableImageSource(dataSrc)) sources.push(dataSrc);
    const srcset = node.attr('srcset');
    if (srcset) {
      for (const entry of srcset.split(',')) {
        const url = entry.trim().split(/\s+/)[0];
        if (isUsableImageSource(url)) sources.push(url);
      }
    }
  }

  // Collect from descendant <img> elements.
  node.find('img').each((_, imgEl) => {
    const img = $(imgEl);
    const src = img.attr('src');
    if (isUsableImageSource(src)) sources.push(src);
    const dataSrc = img.attr('data-src');
    if (isUsableImageSource(dataSrc)) sources.push(dataSrc);
    const srcset = img.attr('srcset');
    if (srcset) {
      for (const entry of srcset.split(',')) {
        const url = entry.trim().split(/\s+/)[0];
        if (isUsableImageSource(url) && !sources.includes(url)) {
          sources.push(url);
        }
      }
    }
  });

  return sources;
}

// ─── Element matching ─────────────────────────────────────────────────────────

/**
 * Try to find a given element (from its outerHTML) within a full-page
 * Cheerio document. Matching strategy:
 *   1. If the element has an `id`, match by `#id`.
 *   2. Otherwise, match by tag + stable data-* attributes + class.
 *   3. If no match, return the first element with the same tag name
 *      and identical class attribute (best-effort).
 *
 * Returns `null` if no reasonable match found.
 */
function findElementByOuterHTML(
  $: cheerio.CheerioAPI,
  outerHTML: string,
): cheerio.Element | null {
  // Parse the outerHTML in a separate Cheerio instance.
  const el$ = cheerio.load(outerHTML);
  const contents = el$.root().contents();
  const first = contents.first();
  const rootAny = first.get(0);
  if (!rootAny || rootAny.type !== 'tag') return null;
  const rootEl = rootAny as cheerio.Element;

  const tag = rootEl.name ?? 'div';
  const rootNode = el$(rootEl);

  /** Helper: return the first element from a Cheerio selection, or null. */
  const firstEl = (sel: ReturnType<typeof $>): cheerio.Element | null => {
    const n = sel.get(0);
    return n && n.type === 'tag' ? (n as cheerio.Element) : null;
  };

  // Strategy 1: match by id.
  const id = rootNode.attr('id');
  if (id && !id.startsWith('_')) {
    const safeId = id.replace(/(["'\\\s\[\]:.])/g, '\\$1');
    const byId = $(`#${safeId}`);
    const el = firstEl(byId);
    if (el && byId.length === 1) return el;
  }

  // Strategy 2: match by tag + stable data-* attributes.
  const stableAttrs = [
    'data-testid',
    'data-test',
    'data-cy',
    'data-qa',
    'data-product-id',
    'data-product-sku',
    'itemprop',
  ];
  for (const attr of stableAttrs) {
    const value = rootNode.attr(attr);
    if (!value) continue;
    const sel = `${tag}[${attr}="${value.replace(/"/g, '\\"')}"]`;
    const matches = $(sel);
    if (matches.length === 1) {
      const el = firstEl(matches);
      if (el) return el;
    }
    if (matches.length > 1) {
      // Multiple matches — try narrowing with class.
      const cls = rootNode.attr('class');
      if (cls) {
        const narrowed = $(`${sel}.${cls.split(/\s+/).filter(Boolean).join('.')}`);
        const el = firstEl(narrowed);
        if (el && narrowed.length === 1) return el;
      }
      // Return the first match (best-effort).
      const el = firstEl(matches);
      if (el) return el;
    }
  }

  // Strategy 3: match by tag + class (best-effort).
  const cls = rootNode.attr('class');
  if (cls) {
    const selector = `${tag}.${cls.split(/\s+/).filter(Boolean).join('.')}`;
    const byClass = $(selector);
    const el = firstEl(byClass);
    if (el) return el;
  }

  // Strategy 4: first element with the same tag (weakest match).
  const byTag = $(tag);
  const el = firstEl(byTag);
  if (el) return el;

  return null;
}

// ─── Route handler ─────────────────────────────────────────────────────────────

/**
 * POST /profile-tooling/generate-selector
 *
 * Accepts `{ html: string, outerHTML: string }` and returns a stable
 * CSS selector for the element described by `outerHTML` within the
 * full page `html`.
 */
export function handleGenerateSelector(
  req: IncomingMessage,
  res: ServerResponse,
): void {
  const chunks: Buffer[] = [];

  req.on('data', (c: Buffer) => {
    chunks.push(c);
  });

  req.on('end', async () => {
    try {
      const rawBody = Buffer.concat(chunks).toString();
      let parsed;
      try {
        parsed = JSON.parse(rawBody);
      } catch {
        res.writeHead(400, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ ok: false, error: 'Invalid JSON body' }));
        return;
      }

      const validation = GenerateSelectorRequestSchema.safeParse(parsed);
      if (!validation.success) {
        res.writeHead(400, { 'Content-Type': 'application/json' });
        res.end(
          JSON.stringify({
            ok: false,
            error: 'Invalid request',
            details: validation.error.issues.map((i) => ({
              path: i.path.map((p) => String(p)).join('.'),
              message: i.message,
            })),
          }),
        );
        return;
      }

      const request = validation.data;
      const result: GenerateSelectorResponse = await generateSelector(
        request.html,
        request.outerHTML,
      );

      res.writeHead(200, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify(result));
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      process.stderr.write(`[generate-selector] Uncaught error: ${msg}\n`);

      // Build a minimal valid response with the error in warnings.
      const fallback = GenerateSelectorResponseSchema.parse({
        selector: '',
        stability: 'low',
        extractedText: null,
        extractedImages: [],
        matchCount: 0,
        warnings: [`Uncaught error: ${msg}`],
      });
      res.writeHead(200, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify(fallback));
    }
  });
}

// ─── Core logic ────────────────────────────────────────────────────────────────

async function generateSelector(
  html: string,
  outerHTML: string,
): Promise<GenerateSelectorResponse> {
  const warnings: string[] = [];

  // Load the full page HTML.
  const $ = cheerio.load(html);

  // Find the element described by outerHTML in the page.
  const el = findElementByOuterHTML($, outerHTML);
  if (!el) {
    // Fallback: try generating from the outerHTML alone.
    const el$ = cheerio.load(outerHTML);
    const contents = el$.root().contents();
    const first = contents.first();
    const rootAny = first.get(0);
    if (!rootAny || rootAny.type !== 'tag') {
      return {
        selector: '',
        stability: 'low',
        extractedText: null,
        extractedImages: [],
        matchCount: 0,
        warnings: ['Could not find the pasted element in the page HTML'],
      };
    }
    const rootEl = rootAny as cheerio.Element;
    const fallbackResult = buildStableSelector(el$, rootEl);
    warnings.push(
      'Could not match element in full page DOM. Selector generated from pasted HTML alone — uniqueness not verified.',
    );
    const text = el$(rootEl).text().replace(/\s+/g, ' ').trim();
    const images = collectImageSourcesFromElement(el$, rootEl);
    return {
      selector: fallbackResult.selector,
      stability: 'low', // can't verify uniqueness, downgrade to low
      extractedText: text || null,
      extractedImages: images,
      matchCount: 1,
      warnings,
    };
  }

  // Generate a stable selector for the matched element.
  const result = buildStableSelector($, el);

  // Validate the selector syntax.
  if (!isSupportedSelectorSyntax(result.selector)) {
    warnings.push(`Generated selector "${result.selector}" uses unsupported syntax`);
  }

  // Count matches in the full page to verify uniqueness.
  let matchCount: number;
  try {
    matchCount = $(result.selector).length;
    if (matchCount > 1) {
      warnings.push(
        `Selector matches ${matchCount} elements — may not be unique enough`,
      );
    }
  } catch {
    warnings.push('Could not count selector matches');
    matchCount = 1;
  }

  // Extract text content.
  const text = $(result.selector).first().text().replace(/\s+/g, ' ').trim();

  // Extract image sources.
  const images = collectImageSourcesFromElement($, el);

  return {
    selector: result.selector,
    stability: result.stability,
    extractedText: text || null,
    extractedImages: images,
    matchCount,
    warnings,
  };
}
