import fs from 'fs';
import path from 'path';
import { buildProductsXml } from './xml-builder';
import { deterministicStringify } from '../git/deterministic-json';
import type { Product } from '../shared/types';

export interface ExportPackageResult {
  exportDir: string;
  xmlPath: string;
  manifestPath: string;
  instructionsPath: string;
  productCount: number;
}

/**
 * Create an export package for a set of changed products.
 * Generates XML, manifest, and upload instructions.
 */
export function createExportPackage(
  workspacePath: string,
  changeSetId: string,
  products: Product[],
  options?: {
    xmlVersion?: string;
    newProductTag?: string;
    changeSetTitle?: string;
  },
): ExportPackageResult {
  const exportDir = path.join(workspacePath, 'exports', changeSetId);
  if (!fs.existsSync(exportDir)) {
    fs.mkdirSync(exportDir, { recursive: true });
  }

  // Generate XML
  const xml = buildProductsXml(products, {
    xmlVersion: options?.xmlVersion,
    newProductTag: options?.newProductTag,
  });

  const xmlPath = path.join(exportDir, 'shopsite-products.xml');
  fs.writeFileSync(xmlPath, xml, 'utf-8');

  // Generate manifest
  const manifest = {
    schemaVersion: 1,
    changeSetId,
    changeSetTitle: options?.changeSetTitle ?? changeSetId,
    generatedAt: new Date().toISOString(),
    productCount: products.length,
    productSkus: products.map(p => p.sku),
    xmlVersion: options?.xmlVersion ?? '15.0',
    notes: 'Export package for ShopSite product import.',
  };

  const manifestPath = path.join(exportDir, 'manifest.json');
  fs.writeFileSync(manifestPath, deterministicStringify(manifest), 'utf-8');

  // Generate upload instructions
  const instructionsPath = path.join(exportDir, 'upload-instructions.md');
  const instructions = generateInstructions(products.length, changeSetId);
  fs.writeFileSync(instructionsPath, instructions, 'utf-8');

  return {
    exportDir,
    xmlPath,
    manifestPath,
    instructionsPath,
    productCount: products.length,
  };
}

function generateInstructions(productCount: number, changeSetId: string): string {
  return `# ShopSite CMS Export — Upload Instructions

## Overview

This export package contains ${productCount} product(s) from change set "${changeSetId}".

## Files

- \`shopsite-products.xml\` — Product XML data to import
- \`manifest.json\` — Export metadata
- \`upload-instructions.md\` — This file

## How to Import

### Option 1: Direct XML upload (if you have CGI access)

1. Open a browser and go to your ShopSite admin backoffice.
2. Navigate to the **Database Upload** tool.
3. Upload \`shopsite-products.xml\` using the form.
4. Set the **Match Upload Fields** to **SKU** (or your configured matching key).
5. Set **Add New Records** to **Yes**.
6. Review the import results page.
7. If prompted, run \`dbmake.cgi\` with the returned parameters.

### Option 2: MIME multipart upload (automated)

If you have a script or integration tool:

1. POST \`shopsite-products.xml\` to \`dbupload.cgi\` as a MIME multipart form with:
   - \`clientApp=1\`
   - \`dbname=products\`
   - \`uniqueName=SKU\`
   - \`newRecords=yes\`
   - \`defer_linking=no\`

2. After upload, call \`dbmake.cgi\` with the \`return_string\` **exactly as returned**.
3. After import, regenerate/publish the store so changes are visible to shoppers:
   - Visit \`generate.cgi\` with \`clientApp=1\`, \`htmlpages=1\`, \`index=1\`
   - Or use your ShopSite admin's **Publish** feature.

## Important Notes

- **Authentication** for automated CGI calls is environment-specific and may require Basic auth, IP whitelisting, or browser session cookies.
- This import will **update existing products** (matched by SKU) and **create new ones** for SKUs not found in ShopSite.
- **Unmatched products** in the source XML that do not have a valid SKU may be skipped or fail.
- After import, always **publish/regenerate** the storefront or shoppers will not see the changes.
- If you encounter unexpected results, export a fresh sample from ShopSite \`db_xml.cgi\` and compare the XML structure.

## ShopSite Documentation Reference

The import workflow follows the documented ShopSite automated database XML upload flow:
- Database Automated XML Upload/Download
- MIME Encoded XML Upload
- Database XML Upload/Download SDK

## v1 Scope Note

This export package was generated by ShopSite CMS v1, which supports product imports only.
Page imports and media uploads are not yet supported.
`;
}
