// fallow-ignore-file unused-export

/**
 * Approved Bay State Pet & Garden Supply v2 seed (Milestone 7 content).
 *
 * This is the reviewed seed that the Milestone 3 generator turns into a
 * preview-valid v2 candidate. Nothing here is activated automatically; the
 * caller must pass the generated candidate through `config-store`.
 *
 * Product Types: the 13 historically committed types plus the approved
 * eight-type expansion (21 total).
 *
 * Reviewed ShopSite field mappings (verified against the live ShopSite
 * Extra Fields configuration):
 *   Brand → ProductField16, Pet Type → ProductField17, Lifestage → ProductField18,
 *   Pet Size → ProductField19, Special Diet → ProductField20, Health Feature → ProductField21,
 *   Food Form → ProductField22, Flavor → ProductField23, Category → ProductField24,
 *   Product Type → ProductField25, Product Feature → ProductField26, Size → ProductField27,
 *   Material → ProductField28, Color → ProductField29, Packaging Type → ProductField30,
 *   Product Cross Sell → ProductField32, Ingredients/Nutrition → ProductField8.
 * ProductField31 (Product Category) is intentionally NOT mapped (the store does not use it).
 */

import type { BayStateSeed } from '../config-generator';

const createdAt = '2026-08-01T12:00:00.000Z';

const disabledFeature = () => ({
  state: 'disabled' as const,
  qualificationReceiptDigest: null,
  activatedBy: null,
  activatedAt: null,
});

export const BayStatePetGardenSeed: BayStateSeed = {
  name: 'Bay State Pet & Garden Supply',
  revision: 'bay-state-v2',
  createdAt,

  // ── Approved Product Types (60+ across 10 Departments) ───────────────────
  productTypes: [
    // Department 1: Pet Supplies
    { id: 'dog-food-dry', name: 'Dry Dog Food', description: 'Dry dog food (kibble).' },
    { id: 'dog-food-wet', name: 'Wet Dog Food', description: 'Canned and pouch wet dog food.' },
    { id: 'dog-treats', name: 'Dog Treats', description: 'Treats and chews for dogs.' },
    { id: 'dog-toys', name: 'Dog Toys', description: 'Toys for dogs.' },
    { id: 'dog-crates-kennels', name: 'Dog Crates & Kennels', description: 'Wire crates, travel kennels, and outdoor dog runs.' },
    { id: 'dog-waste-bags', name: 'Dog Waste Bags', description: 'Dog waste bag rolls and dispensers.' },
    { id: 'cat-food-dry', name: 'Dry Cat Food', description: 'Dry cat food (kibble).' },
    { id: 'cat-food-wet', name: 'Wet Cat Food', description: 'Canned and pouch wet cat food.' },
    { id: 'cat-treats', name: 'Cat Treats', description: 'Treats for cats.' },
    { id: 'cat-toys', name: 'Cat Toys', description: 'Toys for cats.' },
    { id: 'cat-litter', name: 'Cat Litter', description: 'Cat litter and litter accessories.' },
    { id: 'pet-beds', name: 'Pet Beds', description: 'Dog beds, cat beds, and orthopedic pet pads.' },
    { id: 'grooming', name: 'Grooming', description: 'Pet grooming supplies, shampoos, and tools.' },
    { id: 'supplements', name: 'Supplements', description: 'Pet dietary supplements and vitamins.' },
    { id: 'collars-leashes', name: 'Collars & Leashes', description: 'Collars, leashes, harnesses, and tags.' },
    { id: 'flea-tick-treatment', name: 'Flea & Tick Treatment', description: 'Flea and tick prevention and treatment products.' },
    { id: 'small-animal-feed-bedding', name: 'Small Animal Feed & Bedding', description: 'Rabbit pellets, guinea pig food, timothy hay, and bedding.' },

    // Department 2: Livestock & Farm Animals
    { id: 'poultry-feed', name: 'Poultry Feed', description: 'Chicken layer crumbles, starter mash, duck, and game bird feed.' },
    { id: 'poultry-coops-equipment', name: 'Poultry Coops & Equipment', description: 'Chicken coops, brooders, chick waterers, and nesting boxes.' },
    { id: 'cattle-feed', name: 'Cattle Feed', description: 'Beef and dairy feed, mineral blocks, and calf milk replacer.' },
    { id: 'goat-sheep-feed', name: 'Goat & Sheep Feed', description: 'Goat feed, sheep feed, sweet feed, and mineral tubs.' },
    { id: 'pig-swine-feed', name: 'Pig & Swine Feed', description: 'Pig grower feed, sow pellets, and mini pig food.' },
    { id: 'stock-tanks-waterers', name: 'Stock Tanks & Waterers', description: 'Galvanized and poly stock tanks, heated pails, and auto waterers.' },
    { id: 'livestock-feeders', name: 'Livestock Feeders', description: 'Hay racks, creep feeders, fence feeders, and mineral feeders.' },
    { id: 'livestock-health-dewormers', name: 'Livestock Health & Dewormers', description: 'Dewormers, udder care, wound spray, syringes, and antiseptics.' },
    { id: 'fly-insect-control-livestock', name: 'Fly & Pest Control for Livestock', description: 'Pour-on insecticides, fly sprays, dust bags, and fly traps.' },
    { id: 'stall-mats-bedding', name: 'Stall Mats & Bedding', description: 'Pine shavings, wood pellets, rubber stall mats, and straw.' },

    // Department 3: Equine / Horse Care
    { id: 'horse-feed', name: 'Horse Feed', description: 'Senior horse feed, performance feed, hay pellets, and beet pulp.' },
    { id: 'horse-treats-supplements', name: 'Horse Treats & Supplements', description: 'Horse treats, joint supplements, electrolyte paste, and hoof care.' },
    { id: 'fly-control-equine', name: 'Equine Fly & Pest Control', description: 'Horse fly sprays, fly masks, fly sheets, and boots.' },
    { id: 'equine-grooming-hoof', name: 'Equine Grooming & Hoof Care', description: 'Horse shampoos, curry combs, hoof picks, rasps, and thrush care.' },
    { id: 'horse-blankets-tack', name: 'Horse Blankets & Tack', description: 'Turnout sheets, halters, lead ropes, saddles, and pads.' },

    // Department 4: Fencing & Agriculture Containment
    { id: 'electric-fence-chargers', name: 'Electric Fence Chargers', description: 'AC plug-in, solar, and battery powered fence energizers.' },
    { id: 'fence-wire-mesh', name: 'Fence Wire & Mesh', description: 'Barbed wire, field fence, welded wire, horse fence, and chain link.' },
    { id: 't-posts-wooden-posts', name: 'T-Posts & Wooden Fence Posts', description: 'Steel T-posts, wooden fence posts, and step-in posts.' },
    { id: 'corral-panels-gates', name: 'Corral Panels & Farm Gates', description: 'Tube gates, corral panels, wire mesh gates, and gate hardware.' },
    { id: 'electric-fence-insulators', name: 'Electric Fence Insulators', description: 'T-post insulators, corner insulators, polytape, and polywire.' },
    { id: 'fencing-tools', name: 'Fencing Tools & Accessories', description: 'Fence pliers, post hole diggers, wire strainers, and post drivers.' },

    // Department 5: Heating, Fuel & Climate Control
    { id: 'heating-pellets-wood', name: 'Heating Wood Pellets', description: 'Hardwood and softwood stove pellets and compressed fuel logs.' },
    { id: 'firewood-kindling', name: 'Firewood & Kindling', description: 'Packaged firewood, fire starters, and kindling.' },
    { id: 'propane-heaters', name: 'Propane Heaters', description: 'Radiant propane heaters, forced-air heaters, and tank-top heaters.' },
    { id: 'garage-barn-heaters', name: 'Garage & Barn Heaters', description: 'Heavy-duty electric heaters and kerosene forced-air heaters.' },
    { id: 'coop-barn-heat-lamps', name: 'Coop & Barn Heat Lamps', description: 'Infrared heat lamps, chick heating plates, and coop heaters.' },
    { id: 'stove-pipe-chimney-care', name: 'Stove Pipe & Chimney Care', description: 'Stove pipe, chimney brushes, creosote removers, and gaskets.' },

    // Department 6: Lawn, Garden & Landscaping
    { id: 'lawn-fertilizer', name: 'Lawn Fertilizer', description: 'Granular lawn food, weed & feed, and crabgrass preventer.' },
    { id: 'grass-seed', name: 'Grass Seed', description: 'Turfgrass seed blends, sun & shade mixes, and lawn patch repair.' },
    { id: 'weed-control', name: 'Weed Control', description: 'Selective weed killers, non-selective brush killers, and pre-emergents.' },
    { id: 'insect-control', name: 'Insect & Pest Control', description: 'Grub killer, perimeter pest spray, ant killer, and mole repellent.' },
    { id: 'potting-soil', name: 'Potting Soil & Mulch', description: 'Potting soil, compost, raised bed mix, bark mulch, and peat moss.' },
    { id: 'hand-tools', name: 'Hand Garden Tools', description: 'Shovels, rakes, hoes, pruners, loppers, and trowels.' },
    { id: 'garden-hoses-reels', name: 'Garden Hoses & Reels', description: 'Heavy-duty garden hoses, hose reels, carts, and expandable hoses.' },
    { id: 'sprinklers-nozzles', name: 'Sprinklers & Hose Nozzles', description: 'Oscillating sprinklers, spray nozzles, hose timers, and drip irrigation.' },
    { id: 'plant-food-fertilizer', name: 'Plant Food & Garden Fertilizer', description: 'All-purpose plant food, vegetable fertilizer, and bloom boosters.' },

    // Department 7: Power Equipment & Tools
    { id: 'lawn-mowers', name: 'Lawn Mowers', description: 'Riding mowers, push mowers, and zero-turn mowers.' },
    { id: 'string-trimmers-edgers', name: 'String Trimmers & Edgers', description: 'Gas and cordless string trimmers, lawn edgers, and brush cutters.' },
    { id: 'chainsaws-log-splitters', name: 'Chainsaws & Log Splitters', description: 'Gas and battery chainsaws, bar oil, and log splitters.' },
    { id: 'pressure-washers', name: 'Pressure Washers', description: 'Gas and electric pressure washers, surface cleaners, and detergents.' },
    { id: 'power-tool-accessories', name: 'Power Tool Accessories', description: 'Saw blades, drill bit sets, trimmer line, and replacement chains.' },
    { id: 'air-compressors-hoses', name: 'Air Compressors & Hoses', description: 'Portable air compressors, air hoses, and tire inflators.' },

    // Department 8: Trailer & Towing Equipment
    { id: 'trailer-hitches-balls', name: 'Trailer Hitches & Hitch Balls', description: 'Receiver hitches, hitch balls, ball mounts, and hitch pins.' },
    { id: 'towing-couplers-jacks', name: 'Trailer Couplers & Jacks', description: 'Trailer couplers, A-frame jacks, and swivel jacks.' },
    { id: 'trailer-lights-wiring', name: 'Trailer Lights & Wiring', description: 'LED trailer light kits and 4-way / 7-way wiring harnesses.' },
    { id: 'tie-down-straps-chains', name: 'Tie-Down Straps & Chains', description: 'Ratchet tie-down straps, tow chains, and binder chains.' },

    // Department 9: Wild Bird & Wildlife
    { id: 'bird-food', name: 'Wild Bird Food & Seed', description: 'Black oil sunflower, wild bird seed mixes, nyjer seed, and nectar.' },
    { id: 'suet-cakes', name: 'Suet Cakes', description: 'High-energy suet cakes, peanut suet, and berry suet.' },
    { id: 'wild-bird-feeders', name: 'Wild Bird Feeders', description: 'Tube feeders, hopper feeders, suet feeders, and hummingbird feeders.' },
    { id: 'bird-houses-baths', name: 'Bird Houses & Baths', description: 'Wooden birdhouses, bluebird houses, and birdbaths.' },
    { id: 'deer-wildlife-feed', name: 'Deer & Wildlife Feed', description: 'Whole corn, deer attractant blocks, and food plot seed.' },

    // Department 10: Apparel & Workwear
    { id: 'work-boots', name: 'Work Boots & Barn Boots', description: 'Leather work boots, rubber barn boots, and steel-toe work boots.' },
    { id: 'work-gloves', name: 'Work Gloves', description: 'Leather work gloves, insulated winter gloves, and coated garden gloves.' },
    { id: 'workwear-outerwear', name: 'Workwear Outerwear', description: 'Duck canvas jackets, chore coats, and insulated vests.' },
    { id: 'overalls-coveralls', name: 'Overalls & Coveralls', description: 'Bib overalls and insulated coveralls.' },
  ],

  // ── Attributes ────────────────────────────────────────────────────────────
  attributes: [
    {
      id: 'brand',
      name: 'Brand',
      description: 'Manufacturer or house brand.',
      valueMode: 'freeText',
      canonicalUnit: null,
      allowedValues: [],
      valueAliases: [],
      visualEvidenceEligibility: 'eligible',
      isClaim: false,
      isCompositionAttribute: false,
      group: 'Identity',
      isUniversal: true,
      evidencePolicy: {
        directEvidenceRequired: false,
        forbidAbsenceInference: false,
        allowedSources: ['official_product_page', 'visual_product_evidence'],
        allowVisualEvidence: true,
        allowThirdPartyEvidence: false,
        thirdPartyEvidenceApproval: null,
        manualReviewRequired: true,
      },
    },
    {
      id: 'species',
      name: 'Animal Species',
      description: 'Target animal species.',
      valueMode: 'freeText',
      canonicalUnit: null,
      allowedValues: [],
      valueAliases: [],
      visualEvidenceEligibility: 'eligible',
      isClaim: false,
      isCompositionAttribute: false,
      group: 'Pet',
      isUniversal: false,
    },
    {
      id: 'life-stage',
      name: 'Life Stage',
      description: 'Pet life stage.',
      valueMode: 'controlled',
      canonicalUnit: null,
      allowedValues: ['Adult', 'Puppy', 'Kitten', 'Senior', 'Junior', 'All Life Stages'],
      valueAliases: [],
      visualEvidenceEligibility: 'eligible',
      isClaim: false,
      isCompositionAttribute: false,
      group: 'Pet',
      isUniversal: false,
    },
    {
      id: 'breed-size',
      name: 'Breed Size',
      description: 'Dog breed size category.',
      valueMode: 'controlled',
      canonicalUnit: null,
      allowedValues: ['Small', 'Medium', 'Large', 'Giant', 'Toy', 'All Sizes'],
      valueAliases: [],
      visualEvidenceEligibility: 'eligible',
      isClaim: false,
      isCompositionAttribute: false,
      group: 'Pet',
      isUniversal: false,
    },
    {
      id: 'dietary-features',
      name: 'Dietary Features',
      description: 'Dietary feature claims such as grain-free or high-protein.',
      valueMode: 'freeText',
      canonicalUnit: null,
      allowedValues: [],
      valueAliases: [],
      visualEvidenceEligibility: 'eligible',
      isClaim: true,
      isCompositionAttribute: false,
      group: 'Nutrition',
      isUniversal: false,
    },
    {
      id: 'health-benefits',
      name: 'Health Benefits',
      description: 'Health benefit claims.',
      valueMode: 'freeText',
      canonicalUnit: null,
      allowedValues: [],
      valueAliases: [],
      visualEvidenceEligibility: 'eligible',
      isClaim: true,
      isCompositionAttribute: false,
      group: 'Nutrition',
      isUniversal: false,
    },
    {
      id: 'food-form',
      name: 'Food Form',
      description: 'Physical form of food or feed.',
      valueMode: 'controlled',
      canonicalUnit: null,
      allowedValues: ['Dry Food', 'Wet Food', 'Treat', 'Freeze-Dried Raw', 'Frozen Raw', 'Seed Blend', 'Pellets', 'Crumble', 'Mash', 'Sweet Feed', 'Block', 'Tub', 'Supplement'],
      valueAliases: [],
      visualEvidenceEligibility: 'eligible',
      isClaim: false,
      isCompositionAttribute: false,
      group: 'Nutrition',
      isUniversal: false,
    },
    {
      id: 'flavor',
      name: 'Flavor',
      description: 'Flavor of food or treats.',
      valueMode: 'controlled',
      canonicalUnit: null,
      allowedValues: ['Chicken', 'Beef', 'Lamb', 'Turkey', 'Duck', 'Salmon', 'Tuna', 'Fish', 'Peanut Butter', 'Assorted'],
      valueAliases: [],
      visualEvidenceEligibility: 'eligible',
      isClaim: false,
      isCompositionAttribute: false,
      group: 'Nutrition',
      isUniversal: false,
    },
    {
      id: 'category',
      name: 'Category',
      description: 'Store category classification (ShopSite Facet - Category).',
      valueMode: 'freeText',
      canonicalUnit: null,
      allowedValues: [],
      valueAliases: [],
      visualEvidenceEligibility: 'ineligible',
      isClaim: false,
      isCompositionAttribute: false,
      group: 'Store',
      isUniversal: false,
    },
    {
      id: 'product-type',
      name: 'Product Type',
      description: "The store's product type classification, mirrored as the ShopSite Facet - Product Type value.",
      valueMode: 'freeText',
      canonicalUnit: null,
      allowedValues: [],
      valueAliases: [],
      visualEvidenceEligibility: 'ineligible',
      isClaim: false,
      isCompositionAttribute: false,
      group: 'Identity',
      isUniversal: true,
    },
    {
      id: 'packaging-type',
      name: 'Packaging Type',
      description: 'Primary package form (can/bag/box/tray/pouch).',
      valueMode: 'controlled',
      canonicalUnit: null,
      allowedValues: ['Bag', 'Can', 'Box', 'Tray', 'Pouch', 'Bottle', 'Jar', 'Pail', 'Tub', 'Individual'],
      valueAliases: [],
      visualEvidenceEligibility: 'eligible',
      isClaim: false,
      isCompositionAttribute: false,
      group: 'Packaging',
      isUniversal: false,
    },
    {
      id: 'material',
      name: 'Material',
      description: 'Primary product material.',
      valueMode: 'freeText',
      canonicalUnit: null,
      allowedValues: [],
      valueAliases: [],
      visualEvidenceEligibility: 'eligible',
      isClaim: false,
      isCompositionAttribute: false,
      group: 'Product',
      isUniversal: false,
    },
    {
      id: 'color',
      name: 'Color',
      description: 'Primary product color.',
      valueMode: 'freeText',
      canonicalUnit: null,
      allowedValues: [],
      valueAliases: [],
      visualEvidenceEligibility: 'eligible',
      isClaim: false,
      isCompositionAttribute: false,
      group: 'Product',
      isUniversal: false,
    },
    {
      id: 'size',
      name: 'Size',
      description: 'Size abbreviation (S/M/L) — ShopSite Facet - Size.',
      valueMode: 'freeText',
      canonicalUnit: null,
      allowedValues: [],
      valueAliases: [],
      visualEvidenceEligibility: 'eligible',
      isClaim: false,
      isCompositionAttribute: false,
      group: 'Product',
      isUniversal: false,
    },
    {
      id: 'product-feature',
      name: 'Product Feature',
      description: 'Notable product features (ShopSite Facet - Product Feature).',
      valueMode: 'freeText',
      canonicalUnit: null,
      allowedValues: [],
      valueAliases: [],
      visualEvidenceEligibility: 'eligible',
      isClaim: false,
      isCompositionAttribute: false,
      group: 'Product',
      isUniversal: false,
    },
    {
      id: 'product-cross-sell',
      name: 'Product Cross Sell',
      description: 'Associated SKUs or cross-sell products (ShopSite Product Cross Sell).',
      valueMode: 'freeText',
      canonicalUnit: null,
      allowedValues: [],
      valueAliases: [],
      visualEvidenceEligibility: 'ineligible',
      isClaim: false,
      isCompositionAttribute: false,
      group: 'Product',
      isUniversal: false,
    },
    {
      id: 'nutrition',
      name: 'Ingredients & Nutritional Info',
      description: 'Ingredients and nutritional information.',
      valueMode: 'freeText',
      canonicalUnit: null,
      allowedValues: [],
      valueAliases: [],
      visualEvidenceEligibility: 'eligible',
      isClaim: false,
      isCompositionAttribute: false,
      group: 'Nutrition',
      isUniversal: false,
    },

    // ── Domain Expansion Attributes ──────────────────────────────────────────
    {
      id: 'npk-ratio',
      name: 'N-P-K Ratio',
      description: 'Nitrogen-Phosphorus-Potassium ratio for fertilizers (e.g. 10-10-10, 24-0-11).',
      valueMode: 'freeText',
      canonicalUnit: null,
      allowedValues: [],
      valueAliases: [],
      visualEvidenceEligibility: 'eligible',
      isClaim: false,
      isCompositionAttribute: true,
      group: 'Gardening',
      isUniversal: false,
    },
    {
      id: 'protein-pct',
      name: 'Protein Percentage',
      description: 'Crude protein content percentage for livestock and animal feeds (e.g. 16%, 20%).',
      valueMode: 'freeText',
      canonicalUnit: null,
      allowedValues: [],
      valueAliases: [],
      visualEvidenceEligibility: 'eligible',
      isClaim: false,
      isCompositionAttribute: true,
      group: 'Nutrition',
      isUniversal: false,
    },
    {
      id: 'joule-rating',
      name: 'Joule Rating',
      description: 'Energy output rating in Joules for electric fence energizers (e.g. 0.25 Joules, 2.0 Joules).',
      valueMode: 'freeText',
      canonicalUnit: null,
      allowedValues: [],
      valueAliases: [],
      visualEvidenceEligibility: 'eligible',
      isClaim: false,
      isCompositionAttribute: false,
      group: 'Fencing',
      isUniversal: false,
    },
    {
      id: 'btu-rating',
      name: 'BTU Rating',
      description: 'Heating output capacity in BTUs (e.g. 18,000 BTU, 60,000 BTU).',
      valueMode: 'freeText',
      canonicalUnit: null,
      allowedValues: [],
      valueAliases: [],
      visualEvidenceEligibility: 'eligible',
      isClaim: false,
      isCompositionAttribute: false,
      group: 'Heating',
      isUniversal: false,
    },
    {
      id: 'fuel-type',
      name: 'Fuel Type',
      description: 'Fuel or power source for heaters, splitters, and power equipment.',
      valueMode: 'controlled',
      canonicalUnit: null,
      allowedValues: ['Wood Pellets', 'Propane', 'Kerosene', 'Electric', 'Gasoline', 'Natural Gas', 'Firewood', 'Battery'],
      valueAliases: [],
      visualEvidenceEligibility: 'eligible',
      isClaim: false,
      isCompositionAttribute: false,
      group: 'Heating',
      isUniversal: false,
    },
    {
      id: 'towing-capacity-lbs',
      name: 'Towing Capacity',
      description: 'Maximum towing capacity rating in pounds (e.g. 3,500 lbs, 6,000 lbs).',
      valueMode: 'freeText',
      canonicalUnit: null,
      allowedValues: [],
      valueAliases: [],
      visualEvidenceEligibility: 'eligible',
      isClaim: false,
      isCompositionAttribute: false,
      group: 'Towing',
      isUniversal: false,
    },
    {
      id: 'safety-toe-type',
      name: 'Safety Toe Type',
      description: 'Work boot safety toe classification.',
      valueMode: 'controlled',
      canonicalUnit: null,
      allowedValues: ['Steel Toe', 'Composite Toe', 'Soft Toe', 'Alloy Toe'],
      valueAliases: [],
      visualEvidenceEligibility: 'eligible',
      isClaim: false,
      isCompositionAttribute: false,
      group: 'Apparel',
      isUniversal: false,
    },
    {
      id: 'hose-length',
      name: 'Hose Length',
      description: 'Garden or air hose length.',
      valueMode: 'controlled',
      canonicalUnit: null,
      allowedValues: ['25 ft', '50 ft', '75 ft', '100 ft'],
      valueAliases: [],
      visualEvidenceEligibility: 'eligible',
      isClaim: false,
      isCompositionAttribute: false,
      group: 'Gardening',
      isUniversal: false,
    },
  ],

  // ── Profile templates (expanded per Product Type by the generator) ───────
  profileTemplates: [
    {
      id: 'pet-food',
      name: 'Pet Food',
      productTypeIds: [
        'dog-food-dry', 'dog-food-wet', 'dog-treats',
        'cat-food-dry', 'cat-food-wet', 'cat-treats',
        'supplements',
      ],
      attributes: [
        { attributeId: 'food-form', required: false, cardinality: 'single' },
        { attributeId: 'flavor', required: false, cardinality: 'single' },
        { attributeId: 'species', required: false, cardinality: 'single' },
        { attributeId: 'life-stage', required: false, cardinality: 'single' },
        { attributeId: 'breed-size', required: false, cardinality: 'single' },
        { attributeId: 'dietary-features', required: false, cardinality: 'single' },
        { attributeId: 'health-benefits', required: false, cardinality: 'single' },
        { attributeId: 'nutrition', required: false, cardinality: 'single' },
        { attributeId: 'product-cross-sell', required: false, cardinality: 'single' },
      ],
    },
    {
      id: 'pet-accessory',
      name: 'Pet Accessory',
      productTypeIds: [
        'dog-toys', 'cat-toys', 'grooming', 'dog-waste-bags',
        'collars-leashes', 'flea-tick-treatment', 'cat-litter',
        'dog-crates-kennels', 'pet-beds',
      ],
      attributes: [
        { attributeId: 'material', required: false, cardinality: 'single' },
        { attributeId: 'color', required: false, cardinality: 'single' },
        { attributeId: 'size', required: false, cardinality: 'single' },
        { attributeId: 'product-feature', required: false, cardinality: 'single' },
        { attributeId: 'product-cross-sell', required: false, cardinality: 'single' },
      ],
    },
    {
      id: 'livestock-feed',
      name: 'Livestock & Animal Feed',
      productTypeIds: [
        'poultry-feed', 'cattle-feed', 'goat-sheep-feed',
        'pig-swine-feed', 'horse-feed', 'small-animal-feed-bedding',
      ],
      attributes: [
        { attributeId: 'food-form', required: false, cardinality: 'single' },
        { attributeId: 'packaging-type', required: false, cardinality: 'single' },
        { attributeId: 'nutrition', required: false, cardinality: 'single' },
        { attributeId: 'product-cross-sell', required: false, cardinality: 'single' },
      ],
    },
    {
      id: 'livestock-equipment',
      name: 'Livestock Equipment & Stall Care',
      productTypeIds: [
        'poultry-coops-equipment', 'stock-tanks-waterers', 'livestock-feeders',
        'livestock-health-dewormers', 'fly-insect-control-livestock', 'stall-mats-bedding',
        'fly-control-equine', 'equine-grooming-hoof', 'horse-blankets-tack', 'horse-treats-supplements',
      ],
      attributes: [
        { attributeId: 'material', required: false, cardinality: 'single' },
        { attributeId: 'size', required: false, cardinality: 'single' },
        { attributeId: 'packaging-type', required: false, cardinality: 'single' },
        { attributeId: 'product-feature', required: false, cardinality: 'single' },
        { attributeId: 'product-cross-sell', required: false, cardinality: 'single' },
      ],
    },
    {
      id: 'fencing',
      name: 'Fencing & Containment',
      productTypeIds: [
        'electric-fence-chargers', 'fence-wire-mesh', 't-posts-wooden-posts',
        'corral-panels-gates', 'electric-fence-insulators', 'fencing-tools',
      ],
      attributes: [
        { attributeId: 'material', required: false, cardinality: 'single' },
        { attributeId: 'size', required: false, cardinality: 'single' },
        { attributeId: 'product-feature', required: false, cardinality: 'single' },
        { attributeId: 'product-cross-sell', required: false, cardinality: 'single' },
      ],
    },
    {
      id: 'heating',
      name: 'Heating, Fuel & Climate',
      productTypeIds: [
        'heating-pellets-wood', 'firewood-kindling', 'propane-heaters',
        'garage-barn-heaters', 'coop-barn-heat-lamps', 'stove-pipe-chimney-care',
      ],
      attributes: [
        { attributeId: 'packaging-type', required: false, cardinality: 'single' },
        { attributeId: 'product-feature', required: false, cardinality: 'single' },
        { attributeId: 'product-cross-sell', required: false, cardinality: 'single' },
      ],
    },
    {
      id: 'garden',
      name: 'Lawn & Garden',
      productTypeIds: [
        'lawn-fertilizer', 'grass-seed', 'weed-control', 'insect-control',
        'potting-soil', 'hand-tools', 'garden-hoses-reels', 'sprinklers-nozzles',
        'plant-food-fertilizer',
      ],
      attributes: [
        { attributeId: 'category', required: false, cardinality: 'single' },
        { attributeId: 'packaging-type', required: false, cardinality: 'single' },
        { attributeId: 'material', required: false, cardinality: 'single' },
        { attributeId: 'size', required: false, cardinality: 'single' },
        { attributeId: 'product-feature', required: false, cardinality: 'single' },
        { attributeId: 'product-cross-sell', required: false, cardinality: 'single' },
      ],
    },
    {
      id: 'power-equipment',
      name: 'Power Equipment & Tools',
      productTypeIds: [
        'lawn-mowers', 'string-trimmers-edgers', 'chainsaws-log-splitters',
        'pressure-washers', 'power-tool-accessories', 'air-compressors-hoses',
      ],
      attributes: [
        { attributeId: 'material', required: false, cardinality: 'single' },
        { attributeId: 'product-feature', required: false, cardinality: 'single' },
        { attributeId: 'product-cross-sell', required: false, cardinality: 'single' },
      ],
    },
    {
      id: 'towing',
      name: 'Trailer & Towing',
      productTypeIds: [
        'trailer-hitches-balls', 'towing-couplers-jacks',
        'trailer-lights-wiring', 'tie-down-straps-chains',
      ],
      attributes: [
        { attributeId: 'material', required: false, cardinality: 'single' },
        { attributeId: 'size', required: false, cardinality: 'single' },
        { attributeId: 'product-feature', required: false, cardinality: 'single' },
        { attributeId: 'product-cross-sell', required: false, cardinality: 'single' },
      ],
    },
    {
      id: 'wild-bird',
      name: 'Wild Bird & Wildlife',
      productTypeIds: [
        'bird-food', 'suet-cakes', 'wild-bird-feeders',
        'bird-houses-baths', 'deer-wildlife-feed',
      ],
      attributes: [
        { attributeId: 'food-form', required: false, cardinality: 'single' },
        { attributeId: 'packaging-type', required: false, cardinality: 'single' },
        { attributeId: 'product-feature', required: false, cardinality: 'single' },
        { attributeId: 'product-cross-sell', required: false, cardinality: 'single' },
      ],
    },
    {
      id: 'workwear',
      name: 'Apparel & Workwear',
      productTypeIds: [
        'work-boots', 'work-gloves', 'workwear-outerwear', 'overalls-coveralls',
      ],
      attributes: [
        { attributeId: 'material', required: false, cardinality: 'single' },
        { attributeId: 'color', required: false, cardinality: 'single' },
        { attributeId: 'size', required: false, cardinality: 'single' },
        { attributeId: 'product-feature', required: false, cardinality: 'single' },
        { attributeId: 'product-cross-sell', required: false, cardinality: 'single' },
      ],
    },
  ],

  // ── Reviewed ShopSite field mappings (verified against live Extra Fields) ─
  mappings: [
    { id: 'brand-mapping', attributeId: 'brand', catalogField: 'ProductField16', serialization: { kind: 'scalar', prefix: '', suffix: '' } },
    { id: 'species-mapping', attributeId: 'species', catalogField: 'ProductField17', serialization: { kind: 'scalar', prefix: '', suffix: '' } },
    { id: 'life-stage-mapping', attributeId: 'life-stage', catalogField: 'ProductField18', serialization: { kind: 'scalar', prefix: '', suffix: '' } },
    { id: 'breed-size-mapping', attributeId: 'breed-size', catalogField: 'ProductField19', serialization: { kind: 'scalar', prefix: '', suffix: '' } },
    { id: 'dietary-features-mapping', attributeId: 'dietary-features', catalogField: 'ProductField20', serialization: { kind: 'scalar', prefix: '', suffix: '' } },
    { id: 'health-benefits-mapping', attributeId: 'health-benefits', catalogField: 'ProductField21', serialization: { kind: 'scalar', prefix: '', suffix: '' } },
    { id: 'food-form-mapping', attributeId: 'food-form', catalogField: 'ProductField22', serialization: { kind: 'scalar', prefix: '', suffix: '' } },
    { id: 'flavor-mapping', attributeId: 'flavor', catalogField: 'ProductField23', serialization: { kind: 'scalar', prefix: '', suffix: '' } },
    { id: 'category-mapping', attributeId: 'category', catalogField: 'ProductField24', serialization: { kind: 'scalar', prefix: '', suffix: '' } },
    { id: 'product-type-mapping', attributeId: 'product-type', catalogField: 'ProductField25', serialization: { kind: 'scalar', prefix: '', suffix: '' } },
    { id: 'product-feature-mapping', attributeId: 'product-feature', catalogField: 'ProductField26', serialization: { kind: 'scalar', prefix: '', suffix: '' } },
    { id: 'size-mapping', attributeId: 'size', catalogField: 'ProductField27', serialization: { kind: 'scalar', prefix: '', suffix: '' } },
    { id: 'material-mapping', attributeId: 'material', catalogField: 'ProductField28', serialization: { kind: 'scalar', prefix: '', suffix: '' } },
    { id: 'color-mapping', attributeId: 'color', catalogField: 'ProductField29', serialization: { kind: 'scalar', prefix: '', suffix: '' } },
    { id: 'packaging-type-mapping', attributeId: 'packaging-type', catalogField: 'ProductField30', serialization: { kind: 'scalar', prefix: '', suffix: '' } },
    { id: 'product-cross-sell-mapping', attributeId: 'product-cross-sell', catalogField: 'ProductField32', serialization: { kind: 'scalar', prefix: '', suffix: '' } },
    { id: 'nutrition-mapping', attributeId: 'nutrition', catalogField: 'ProductField8', serialization: { kind: 'scalar', prefix: '', suffix: '' } },
  ],

  // ── Curation targets ──────────────────────────────────────────────────────
  // Product Type enabled; Page target disabled/mandatory:false/required:false;
  // claim/composition fields (dietary-features, health-benefits) have no
  // enabled targets and stay inactive.
  curationTargets: [
    {
      id: 'primary-product-type',
      kind: 'product_type',
      label: 'Primary Product Type',
      enabled: true,
      mandatory: false,
      selectionMode: 'single',
      attributeId: null,
      catalogField: null,
      optionSource: 'configured',
      required: true,
      sortOrder: 0,
    },
    { id: 'brand-target', kind: 'product_field', label: 'Brand', enabled: true, mandatory: false, selectionMode: 'single', attributeId: 'brand', catalogField: 'ProductField16', optionSource: 'configured', required: false, sortOrder: 10 },
    { id: 'species-target', kind: 'product_field', label: 'Animal Species', enabled: true, mandatory: false, selectionMode: 'single', attributeId: 'species', catalogField: 'ProductField17', optionSource: 'configured', required: false, sortOrder: 11 },
    { id: 'life-stage-target', kind: 'product_field', label: 'Life Stage', enabled: true, mandatory: false, selectionMode: 'single', attributeId: 'life-stage', catalogField: 'ProductField18', optionSource: 'configured', required: false, sortOrder: 12 },
    { id: 'breed-size-target', kind: 'product_field', label: 'Breed Size', enabled: true, mandatory: false, selectionMode: 'single', attributeId: 'breed-size', catalogField: 'ProductField19', optionSource: 'configured', required: false, sortOrder: 13 },
    { id: 'food-form-target', kind: 'product_field', label: 'Food Form', enabled: true, mandatory: false, selectionMode: 'single', attributeId: 'food-form', catalogField: 'ProductField22', optionSource: 'configured', required: false, sortOrder: 14 },
    { id: 'flavor-target', kind: 'product_field', label: 'Flavor', enabled: true, mandatory: false, selectionMode: 'single', attributeId: 'flavor', catalogField: 'ProductField23', optionSource: 'configured', required: false, sortOrder: 15 },
    { id: 'category-target', kind: 'product_field', label: 'Category', enabled: true, mandatory: false, selectionMode: 'single', attributeId: 'category', catalogField: 'ProductField24', optionSource: 'configured', required: false, sortOrder: 16 },
    { id: 'product-type-target', kind: 'product_field', label: 'Product Type', enabled: true, mandatory: false, selectionMode: 'single', attributeId: 'product-type', catalogField: 'ProductField25', optionSource: 'configured', required: false, sortOrder: 17 },
    { id: 'packaging-type-target', kind: 'product_field', label: 'Packaging Type', enabled: true, mandatory: false, selectionMode: 'single', attributeId: 'packaging-type', catalogField: 'ProductField30', optionSource: 'configured', required: false, sortOrder: 18 },
    { id: 'material-target', kind: 'product_field', label: 'Material', enabled: true, mandatory: false, selectionMode: 'single', attributeId: 'material', catalogField: 'ProductField28', optionSource: 'configured', required: false, sortOrder: 19 },
    { id: 'color-target', kind: 'product_field', label: 'Color', enabled: true, mandatory: false, selectionMode: 'single', attributeId: 'color', catalogField: 'ProductField29', optionSource: 'configured', required: false, sortOrder: 20 },
    { id: 'size-target', kind: 'product_field', label: 'Size', enabled: true, mandatory: false, selectionMode: 'single', attributeId: 'size', catalogField: 'ProductField27', optionSource: 'configured', required: false, sortOrder: 21 },
    { id: 'product-feature-target', kind: 'product_field', label: 'Product Feature', enabled: true, mandatory: false, selectionMode: 'single', attributeId: 'product-feature', catalogField: 'ProductField26', optionSource: 'configured', required: false, sortOrder: 22 },
    { id: 'product-cross-sell-target', kind: 'product_field', label: 'Product Cross Sell', enabled: true, mandatory: false, selectionMode: 'single', attributeId: 'product-cross-sell', catalogField: 'ProductField32', optionSource: 'configured', required: false, sortOrder: 23 },
    {
      id: 'store-pages',
      kind: 'page',
      label: 'Category Pages',
      enabled: true,
      mandatory: false,
      selectionMode: 'multiple',
      attributeId: null,
      catalogField: null,
      optionSource: 'live_store',
      required: false,
      sortOrder: 30,
    },
  ],

  brands: [
    // The store's own reviewed canonical brands, carried from the live v1
    // brands.json. The list is deliberately NOT treated as complete: the brand
    // attribute stays free-text (no allowed values) with mandatory manual
    // review, so unknown brands flow through for human approval.
    { id: 'woof', name: 'Woof', aliases: ['WOOF', 'My Woof', 'mywoof'], oldIdAliases: [] },
    { id: 'honest-kitchen', name: 'The Honest Kitchen', aliases: ['HONEST KITCHEN', 'Honest Kitchen', 'thehonestkitchen.com'], oldIdAliases: [] },
    { id: 'dr-marty', name: 'Dr. Marty', aliases: ['DR MARTY', 'Dr Marty', 'DR. MARTY'], oldIdAliases: [] },
    { id: 'blue-buffalo', name: 'Blue Buffalo', aliases: ['BLUE BUFFALO', 'Blue'], oldIdAliases: [] },
    { id: 'tuffy', name: 'Tuffy', aliases: ['TUFFY'], oldIdAliases: [] },
    { id: 'purina', name: 'Purina', aliases: ['PURINA'], oldIdAliases: [] },
  ],

  guidance: [],

  modelPolicy: {
    defaultProvider: 'ollama',
    defaultModel: 'qwen2.5vl:latest',
    providerLocalities: { ollama: 'local' },
    stageOverrides: {},
    imageDataSharing: 'local_only',
    textDataSharing: 'local_only',
    mlFeatures: {
      productionRetrieval: disabledFeature(),
      pageReranking: disabledFeature(),
      confidenceCalibration: disabledFeature(),
      productionEmbeddings: disabledFeature(),
    },
  },

  dataSharing: {
    imagePolicy: 'local_only',
    textPolicy: 'local_only',
    sensitiveDataFiltering: true,
    retentionDays: 90,
  },
};
