import type { Product, CoreProduct, ShopSiteMeta, PreservedFields } from './schemas/product';
import type { FieldRegistryEntry, FieldRegistry } from './schemas/field-registry';
import type { Workspace, ShopSiteConnection } from './schemas/workspace';
import type { ChangeSet, ChangeSetItem } from './schemas/change-set';
import type { SyncJob, SyncJobEvent } from './schemas/sync';
import type { ValidationResult } from './schemas/validation';
import type {
  OnboardingBatch, OnboardingItem, OnboardingSource,
  ExtractionData, CurationData, ColumnMapping, SpreadsheetRow,
  BrandSite, ApiKeyConfig, BatchStatus, ItemStatus,
} from './schemas/onboarding';
import type {
  ClassificationConfig,
  ClassificationManifest,
  ProductTypeConfig,
  ProductAttributeConfig,
  AttributeProfileConfig,
  AttributeMappingConfig,
  CurationTargetConfig,
  GuidanceConfig,
  ModelPolicyConfig,
  DataSharingConfig,
  ClassificationEvidence,
  ClassificationProposal,
  ClassificationProposalDecision,
  ClassificationHistoryEvent,
  ClassificationConfigSnapshotRef,
  ClassificationStageName,
  ClassificationRunStatus,
  ClassificationStageStatus,
  EvidenceSource,
  EvidenceReliability,
  ProposalType,
  ProposalStatus,
  ValueMode,
  Cardinality,
  CurationTargetKind,
  CurationTargetOptionSource,
} from './schemas/classification';

export type {
  Product,
  CoreProduct,
  ShopSiteMeta,
  PreservedFields,
  FieldRegistryEntry,
  FieldRegistry,
  Workspace,
  ShopSiteConnection,
  ChangeSet,
  ChangeSetItem,
  SyncJob,
  SyncJobEvent,
  ValidationResult,
  OnboardingBatch,
  OnboardingItem,
  OnboardingSource,
  ExtractionData,
  CurationData,
  ColumnMapping,
  SpreadsheetRow,
  BrandSite,
  ApiKeyConfig,
  BatchStatus,
  ItemStatus,
  ClassificationConfig,
  ClassificationManifest,
  ProductTypeConfig,
  ProductAttributeConfig,
  AttributeProfileConfig,
  AttributeMappingConfig,
  CurationTargetConfig,
  GuidanceConfig,
  ModelPolicyConfig,
  DataSharingConfig,
  ClassificationEvidence,
  ClassificationProposal,
  ClassificationProposalDecision,
  ClassificationHistoryEvent,
  ClassificationConfigSnapshotRef,
  ClassificationStageName,
  ClassificationRunStatus,
  ClassificationStageStatus,
  EvidenceSource,
  EvidenceReliability,
  ProposalType,
  ProposalStatus,
  ValueMode,
  Cardinality,
  CurationTargetKind,
  CurationTargetOptionSource,
};

/** Syncable product status for a change set item */
export type ProductOperation = 'create' | 'update' | 'archive';
