// ---------------------------------------------------------------------------
// Store Manager notification service (operations console, Issue 3)
//
// Notifications are durable in-app threshold FACTS generated by a
// deterministic rule engine — never model prose. Rules evaluate collector
// snapshots and emit ONLY on threshold crossing or a new source identity
// (edge-triggered), never on every scan. A per-workspace UNIQUE fingerprint
// dedupes repeat chatter. `scheduled_report_new_fingerprint` is a Phase B
// seam seeded disabled.
// ---------------------------------------------------------------------------

import {
  ensureNotificationRules,
  getNotificationRule,
  updateNotificationRuleSnapshot,
  insertNotification,
  listNotifications,
  markNotificationRead,
  countUnreadNotifications,
  getLatestNotificationSequence,
} from '../../db/repositories/store-manager-notification-repo';
import {
  collectInboxCandidates,
  type InboxCandidate,
} from './store-manager-inbox-collectors';
import { findActiveInboxItemByDedupeKey } from './store-manager-inbox-service';
import { hashCanonicalJson } from '../../shared/stable-id';
import type {
  StoreManagerNotification,
  StoreManagerNotificationEvaluation,
  StoreManagerNotificationRuleKind,
} from '../../shared/schemas/store-manager-notification';

export interface NotificationEvaluationDeps {
  /** Injected collector seam (rule-logic tests). */
  collect?: typeof collectInboxCandidates;
  /** Injected clock. */
  now?: () => Date;
}

interface RuleObservation {
  proposalCount: number;
  criticalIssueCount: number;
  failedJobIds: string[];
  imageRepairCount: number;
}

function observe(candidates: InboxCandidate[]): RuleObservation {
  const proposal = candidates.find((c) => c.kind === 'proposals_awaiting_review');
  const critical = candidates.find((c) => c.kind === 'high_severity_catalog_issues');
  const sync = candidates.find((c) => c.kind === 'failed_sync_jobs');
  const image = candidates.filter((c) => c.kind === 'image_repairs_recommended');
  return {
    proposalCount: proposal?.count ?? 0,
    criticalIssueCount: critical?.count ?? 0,
    failedJobIds: (sync?.sourceRefs ?? []).filter((r) => r.kind === 'sync_job').map((r) => r.id),
    imageRepairCount: image.reduce((sum, c) => sum + c.count, 0),
  };
}

function transitionFingerprint(ruleId: string, transitionId: string): string {
  return hashCanonicalJson({ ruleId, transitionId });
}

/** Default enabled/disabled state per rule kind (see repo DEFAULT_NOTIFICATION_RULES). */
const RULE_SEVERITY: Record<StoreManagerNotificationRuleKind, 'info' | 'warning' | 'critical'> = {
  proposal_backlog_exceeded: 'warning',
  critical_issue_count_increased: 'critical',
  sync_failure_appeared: 'critical',
  image_integrity_dropped: 'warning',
  scheduled_report_new_fingerprint: 'info',
};

const MAX_EMITTED_PER_EVALUATION = 20;

/**
 * Evaluate all notification rules against the current deterministic snapshot.
 * Rules are seeded per workspace on first call; disabled rules keep their
 * snapshot untouched (enabling later starts fresh). Returns the emitted
 * notifications and the new latest sequence.
 */
export function evaluateNotificationRules(
  workspaceId: string,
  deps: NotificationEvaluationDeps = {},
): StoreManagerNotificationEvaluation {
  const rules = ensureNotificationRules(workspaceId);
  const collect = deps.collect ?? collectInboxCandidates;
  const candidates = collect(workspaceId);
  const obs = observe(candidates);
  const emitted: StoreManagerNotification[] = [];

  for (const rule of rules) {
    if (!rule.enabled) continue;
    // FIRST evaluation records a baseline only — there is no prior state to
    // transition from, so nothing can cross or increase. This prevents a
    // first-open notification flood while keeping edge-triggered semantics.
    if (!rule.lastSeenSnapshotJson) {
      const firstSnapshot = rule.kind === 'sync_failure_appeared'
        ? { jobIds: obs.failedJobIds.slice(0, 500) }
        : rule.kind === 'proposal_backlog_exceeded'
          ? { count: obs.proposalCount }
          : rule.kind === 'critical_issue_count_increased'
            ? { count: obs.criticalIssueCount }
            : rule.kind === 'image_integrity_dropped'
              ? { count: obs.imageRepairCount }
              : { count: obs.imageRepairCount };
      updateNotificationRuleSnapshot(workspaceId, rule.kind, JSON.stringify(firstSnapshot));
      continue;
    }
    const prev = JSON.parse(rule.lastSeenSnapshotJson) as Record<string, unknown>;
    const next: Record<string, unknown> = { ...prev };

    switch (rule.kind) {
      case 'proposal_backlog_exceeded': {
        const threshold = Number((JSON.parse(rule.configJson) as { threshold?: unknown }).threshold ?? 20);
        const prevCount = Number(prev.count ?? 0);
        const current = obs.proposalCount;
        next.count = current;
        // Edge crossing only: below → at/above. No repeat chatter above.
        if (current >= threshold && prevCount < threshold) {
          const item = findActiveInboxItemByDedupeKey(workspaceId, 'proposals_awaiting_review:catalog:v1');
          emitted.push(
            ...emit(rule.kind, rule, transitionFingerprint(rule.id, `crossed:${current}`), 'warning', 'Proposal backlog',
              `Proposal backlog exceeded: ${current} proposal(s) awaiting review (threshold ${threshold}).`, item?.id ?? null),
          );
        }
        break;
      }
      case 'critical_issue_count_increased': {
        const prevCount = Number(prev.count ?? 0);
        const current = obs.criticalIssueCount;
        next.count = current;
        if (current > prevCount) {
          const item = findActiveInboxItemByDedupeKey(workspaceId, 'high_severity_catalog_issues:catalog:v1');
          emitted.push(
            ...emit(rule.kind, rule, transitionFingerprint(rule.id, `count:${current}`), 'critical', 'Critical catalog issues increased',
              `Critical catalog issues increased from ${prevCount} to ${current}.`, item?.id ?? null),
          );
        }
        break;
      }
      case 'sync_failure_appeared': {
        const prevIds = Array.isArray(prev.jobIds) ? (prev.jobIds as string[]) : [];
        const currentIds = obs.failedJobIds;
        const prevSet = new Set(prevIds);
        const fresh = currentIds.filter((id) => !prevSet.has(id)).slice(0, MAX_EMITTED_PER_EVALUATION);
        next.jobIds = currentIds.slice(0, 500);
        const item = findActiveInboxItemByDedupeKey(workspaceId, 'failed_sync_jobs:sync:v1');
        for (const jobId of fresh) {
          emitted.push(
            ...emit(rule.kind, rule, transitionFingerprint(rule.id, `job:${jobId}`), 'critical', 'Sync failure',
              `Sync job ${jobId.slice(0, 8)} failed. Check sync history for details.`, item?.id ?? null),
          );
        }
        break;
      }
      case 'image_integrity_dropped': {
        const prevCount = Number(prev.count ?? 0);
        const current = obs.imageRepairCount;
        next.count = current;
        if (current > prevCount) {
          emitted.push(
            ...emit(rule.kind, rule, transitionFingerprint(rule.id, `count:${current}`), 'warning', 'Image integrity dropped',
              `Image repairs recommended increased from ${prevCount} to ${current} across change sets.`, null),
          );
        }
        break;
      }
      case 'scheduled_report_new_fingerprint': {
        // Phase B seam: no report fingerprints exist in Phase A, so this rule
        // only records its snapshot and never emits.
        const current = obs.imageRepairCount; // placeholder — replaced by report artifact fingerprints in Issue 4
        next.count = current;
        break;
      }
    }

    updateNotificationRuleSnapshot(workspaceId, rule.kind, JSON.stringify(next));
  }

  return {
    emitted: emitted.slice(0, MAX_EMITTED_PER_EVALUATION),
    latestSequence: getLatestNotificationSequence(workspaceId),
  };
}

function emit(
  ruleKind: StoreManagerNotificationRuleKind,
  rule: { id: string; workspaceId: string; kind: StoreManagerNotificationRuleKind; version: number },
  fingerprint: string,
  severity: 'info' | 'warning' | 'critical',
  title: string,
  message: string,
  inboxItemId: string | null,
): StoreManagerNotification[] {
  const inserted = insertNotification({
    workspaceId: rule.workspaceId,
    ruleId: rule.id,
    ruleKind,
    ruleVersion: rule.version,
    fingerprint,
    severity: RULE_SEVERITY[ruleKind] ?? severity,
    title,
    message: message.slice(0, 2000),
    inboxItemId,
    sourceRunId: null,
  });
  return inserted ? [inserted] : [];
}

export function listNotificationsForWorkspace(
  workspaceId: string,
  opts: { afterSequence?: number | null; limit?: number } = {},
): StoreManagerNotification[] {
  return listNotifications(workspaceId, opts);
}

export function markNotificationReadForWorkspace(workspaceId: string, id: string): boolean {
  return markNotificationRead(workspaceId, id);
}

export function countUnreadNotificationsForWorkspace(workspaceId: string): number {
  return countUnreadNotifications(workspaceId);
}
