/**
 * Store Manager legacy tool builder + policy gate machinery (epic #42,
 * #34/#40).
 *
 * The canonical runtime tool surface lives in the #40 adapter registry
 * (`src/store-manager/runtime/tool-registry.ts` + `src/store-manager/tools/*`).
 * This module keeps the #34 approval gate (`gateToolExecution`,
 * `ApprovalGateError`, `StoreManagerToolContext`) unchanged — the registry
 * reuses it at dispatch time — and provides a thin legacy builder
 * (`createStoreManagerTools`) that wraps the same registry adapters for
 * direct tool-level tests. No raw SQL, fetch, or filesystem code lives here;
 * adapters call workspace-scoped services only.
 */

import { tool } from 'ai';
import type { ToolExecutionOptions, ModelMessage } from 'ai';
import { requireStoreManagerToolPolicy, STORE_MANAGER_TOOL_POLICIES, type StoreManagerToolPolicy } from './store-manager-tool-policy';
import {
  createStoreManagerToolRegistry,
  type StoreManagerToolRegistry,
} from '../../store-manager/runtime/tool-registry';
import type { StoreManagerAdapterContext, StoreManagerToolResult } from '../../store-manager/runtime/contracts';

export interface StoreManagerToolContext {
  workspaceId: string;
  workspacePath: string;
  /**
   * Per-chat execution id generated by the route; binds this tool set to one
   * turn so approvals cannot cross threads/workspaces.
   */
  executionId?: string;
  /** Absolute epoch ms after which this execution context refuses to run. */
  approvalExpiresAt?: number;
}

/**
 * Structured denial for the tool runtime. The AI SDK signature is the first
 * server check; this error is the wrapper's fail-closed second check.
 */
export class ApprovalGateError extends Error {
  readonly code:
    | 'execution_context_missing'
    | 'approval_session_expired'
    | 'approval_required'
    | 'approval_missing'
    | 'approval_denied'
    | 'approval_replay_or_altered';

  constructor(
    code: ApprovalGateError['code'],
    message: string,
  ) {
    super(message);
    this.name = 'ApprovalGateError';
    this.code = code;
  }
}

type AnyToolExecute = (input: unknown, options: ToolExecutionOptions<unknown>) => unknown;

function deepEqual(a: unknown, b: unknown): boolean {
  if (a === b) return true;
  if (a === null || b === null || typeof a !== typeof b) return false;
  if (Array.isArray(a) && Array.isArray(b)) {
    return a.length === b.length && a.every((v, i) => deepEqual(v, b[i]));
  }
  if (typeof a === 'object' && typeof b === 'object') {
    const ka = Object.keys(a as object).sort();
    const kb = Object.keys(b as object).sort();
    return (
      ka.length === kb.length &&
      ka.every((k, i) => k === kb[i] && deepEqual((a as Record<string, unknown>)[k], (b as Record<string, unknown>)[k]))
    );
  }
  return false;
}

/**
 * Determine the approval state for a specific tool call from the model
 * messages that initiated this step. Returns:
 * - 'approved' when a tool-approval-response with approved:true exists for the
 *   approval request bound to this tool call;
 * - 'denied' when the response denied it;
 * - 'pending' when a request exists but no response yet;
 * - 'missing' when no approval request references this tool call at all.
 */
export function approvalStateForToolCall(
  messages: ModelMessage[],
  toolCallId: string,
): 'approved' | 'denied' | 'pending' | 'missing' {
  let approvalId: string | null = null;
  for (const message of messages) {
    if (!Array.isArray(message.content)) continue;
    for (const part of message.content as Array<{ type?: string }>) {
      if (part.type === 'tool-approval-request' && (part as Record<string, unknown>).toolCallId === toolCallId) {
        approvalId = String((part as Record<string, unknown>).approvalId);
      }
    }
  }
  if (!approvalId) return 'missing';

  for (const message of messages) {
    if (!Array.isArray(message.content)) continue;
    for (const part of message.content as Array<{ type?: string }>) {
      if (part.type === 'tool-approval-response' && (part as Record<string, unknown>).approvalId === approvalId) {
        return (part as Record<string, unknown>).approved === true ? 'approved' : 'denied';
      }
    }
  }
  return 'pending';
}

/**
 * Verify the input passed to `execute` is exactly the tool-call input recorded
 * in the approved message history (defense in depth against altered/replayed
 * arguments; the AI SDK HMAC signature is the first check).
 */
export function toolCallInputMatchesReceived(
  messages: ModelMessage[],
  toolCallId: string,
  receivedInput: unknown,
): boolean {
  for (const message of messages) {
    if (!Array.isArray(message.content)) continue;
    for (const part of message.content as Array<{ type?: string }>) {
      if (part.type === 'tool-call' && (part as Record<string, unknown>).toolCallId === toolCallId) {
        return deepEqual((part as Record<string, unknown>).input, receivedInput);
      }
    }
  }
  return false;
}

/**
 * Wrap a tool's execute with the policy gate:
 * 1. a valid server execution context must exist and not be expired;
 * 2. approval-required tools must show an approved approval response for THIS
 *    tool call and the received input must be the exact approved input.
 * Read tools execute without approval but still refuse outside a valid context.
 */
export function gateToolExecution(
  policy: StoreManagerToolPolicy,
  context: StoreManagerToolContext,
  execute: AnyToolExecute,
): AnyToolExecute {
  return async (input, options) => {
    if (!context.executionId || context.executionId.length === 0 || !context.approvalExpiresAt) {
      throw new ApprovalGateError(
        'execution_context_missing',
        'Tool execution requires a server execution context; request was not routed through the Store Manager runtime.',
      );
    }
    if (Date.now() > context.approvalExpiresAt) {
      throw new ApprovalGateError(
        'approval_session_expired',
        'The approval session for this chat turn has expired. Re-send your message to continue.',
      );
    }

    if (policy.requiresApproval) {
      const messages = options?.messages ?? [];
      const state = approvalStateForToolCall(messages, options.toolCallId);
      if (state === 'approved') {
        if (!toolCallInputMatchesReceived(messages, options.toolCallId, input)) {
          throw new ApprovalGateError(
            'approval_replay_or_altered',
            `Tool call "${policy.name}" arguments were altered after approval; execution refused.`,
          );
        }
      } else if (state === 'denied') {
        throw new ApprovalGateError(
          'approval_denied',
          `Execution of "${policy.name}" was denied by the operator.`,
        );
      } else {
        // pending or missing: an approval-required tool was invoked without a
        // signed operator approval for this exact call — fail closed.
        throw new ApprovalGateError(
          'approval_missing',
          `Execution of "${policy.name}" requires explicit operator approval.`,
        );
      }
    }

    return execute(input, options);
  };
}

/** Flatten a registry adapter result into the plain result shape callers of
 * the legacy builder expect (throw paths stay throws; denials stay structured). */
function flattenAdapterResult(result: StoreManagerToolResult): unknown {
  if (result.status === 'ok') return result.data;
  if (result.status === 'no_result') return result.data ?? { success: false, error: result.note };
  if (result.status === 'error') return { success: false, error: result.message, errorCode: result.errorCode };
  return { success: false, error: result.message, denial: result.reasonCode };
}

/**
 * Build the raw AI SDK tool definitions for direct tool-level tests and the
 * #34 approval tests. This is a compatibility builder over the canonical #40
 * adapters; the chat route uses the executor/registry instead.
 */
export function buildStoreManagerToolDefs(
  context: StoreManagerToolContext,
  registry: StoreManagerToolRegistry = createStoreManagerToolRegistry(),
): Record<string, ReturnType<typeof tool>> {
  const out: Record<string, ReturnType<typeof tool>> = {};
  const legacyAdapterCtx: StoreManagerAdapterContext = {
    workspaceId: context.workspaceId,
    workspacePath: context.workspacePath,
    sessionId: context.executionId ?? 'legacy',
    executionId: context.executionId ?? 'legacy',
    deadlineAt: context.approvalExpiresAt ?? Number.MAX_SAFE_INTEGER,
    emit: () => undefined,
  };

  for (const adapter of registry.all()) {
    const policyShape: StoreManagerToolPolicy = {
      name: adapter.name,
      version: adapter.version,
      riskClass: adapter.riskClass,
      sideEffects: adapter.sideEffects,
      requiresApproval: adapter.requiresApproval,
      stateTransition: adapter.stateTransition,
      scopeSummary: adapter.scopeSummary,
    };
    const gated = gateToolExecution(
      policyShape,
      context,
      async (input: unknown): Promise<StoreManagerToolResult> =>
        adapter.execute(input as Record<string, unknown>, legacyAdapterCtx),
    ) as (input: unknown, options: ToolExecutionOptions<unknown>) => Promise<StoreManagerToolResult>;

    out[adapter.name] = (tool({
      description: adapter.description,
      inputSchema: adapter.inputSchema as never,
      execute: async (input: unknown, options: ToolExecutionOptions<unknown>) => {
        const raw = await gated(input, options);
        return flattenAdapterResult(raw);
      },
    }) as unknown) as ReturnType<typeof tool>;
  }

  // Guard: the builder's tool set must exactly match the policy registry so a
  // new adapter without policy metadata fails fast here, not in production.
  const built = Object.keys(out);
  const policyNames = Object.keys(requireAllPolicies());
  for (const name of policyNames) {
    if (!built.includes(name)) {
      throw new Error(`Store Manager policy "${name}" has no adapter; registration drift.`);
    }
  }
  return out;
}

function requireAllPolicies(): Record<string, StoreManagerToolPolicy> {
  return STORE_MANAGER_TOOL_POLICIES;
}

/**
 * The exact set of tool names the runtime exposes, in stable order. Used by
 * tests to prove the tool-policy registry and the generated prompt guidelines
 * name exactly these tools (no drift).
 */
export function getStoreManagerToolNames(registry: StoreManagerToolRegistry = createStoreManagerToolRegistry()): string[] {
  return registry.all().map((a) => a.name);
}

export function createStoreManagerTools(context: StoreManagerToolContext) {
  return buildStoreManagerToolDefs(context);
}
