import { tool, type ToolExecutionOptions, type ModelMessage } from 'ai';
import { z } from 'zod';
import { getDashboardStatsData } from './dashboard-service';
import { getCatalogHealthReport } from './product-service';
import { listProductIndex } from './product-service';
import { getProductFieldAudit, proposeProductFieldNormalization } from './product-field-audit-service';
import {
  generateDeterministicProposals,
  listProposals,
  applyProposal,
  dismissProposal,
} from './product-field-refactor-service';
import { requireStoreManagerToolPolicy, type StoreManagerToolPolicy } from './store-manager-tool-policy';
import { repairChangeSetImagesForWorkspace } from './store-manager-image-repair';

export interface StoreManagerToolContext {
  workspaceId: string;
  workspacePath: string;
  /**
   * Per-chat execution id generated by the route; binds this tool set to one
   * turn so approvals cannot cross threads/workspaces.
   */
  executionId?: string;
  /** Absolute epoch ms after which this execution context refuses to run. */
  approvalExpiresAt?: number;
}

/**
 * Structured denial for the tool runtime. The AI SDK signature is the first
 * server check; this error is the wrapper's fail-closed second check.
 */
export class ApprovalGateError extends Error {
  readonly code:
    | 'execution_context_missing'
    | 'approval_session_expired'
    | 'approval_required'
    | 'approval_missing'
    | 'approval_denied'
    | 'approval_replay_or_altered';

  constructor(
    code: ApprovalGateError['code'],
    message: string,
  ) {
    super(message);
    this.name = 'ApprovalGateError';
    this.code = code;
  }
}

type AnyToolExecute = (input: unknown, options: ToolExecutionOptions<unknown>) => unknown;

function deepEqual(a: unknown, b: unknown): boolean {
  if (a === b) return true;
  if (a === null || b === null || typeof a !== typeof b) return false;
  if (Array.isArray(a) && Array.isArray(b)) {
    return a.length === b.length && a.every((v, i) => deepEqual(v, b[i]));
  }
  if (typeof a === 'object' && typeof b === 'object') {
    const ka = Object.keys(a as object).sort();
    const kb = Object.keys(b as object).sort();
    return (
      ka.length === kb.length &&
      ka.every((k, i) => k === kb[i] && deepEqual((a as Record<string, unknown>)[k], (b as Record<string, unknown>)[k]))
    );
  }
  return false;
}

/**
 * Determine the approval state for a specific tool call from the model
 * messages that initiated this step. Returns:
 * - 'approved' when a tool-approval-response with approved:true exists for the
 *   approval request bound to this tool call;
 * - 'denied' when the response denied it;
 * - 'pending' when a request exists but no response yet;
 * - 'missing' when no approval request references this tool call at all.
 */
function approvalStateForToolCall(
  messages: ModelMessage[],
  toolCallId: string,
): 'approved' | 'denied' | 'pending' | 'missing' {
  let approvalId: string | null = null;
  for (const message of messages) {
    if (!Array.isArray(message.content)) continue;
    for (const part of message.content as Array<{ type?: string }>) {
      if (part.type === 'tool-approval-request' && (part as Record<string, unknown>).toolCallId === toolCallId) {
        approvalId = String((part as Record<string, unknown>).approvalId);
      }
    }
  }
  if (!approvalId) return 'missing';

  for (const message of messages) {
    if (!Array.isArray(message.content)) continue;
    for (const part of message.content as Array<{ type?: string }>) {
      if (part.type === 'tool-approval-response' && (part as Record<string, unknown>).approvalId === approvalId) {
        return (part as Record<string, unknown>).approved === true ? 'approved' : 'denied';
      }
    }
  }
  return 'pending';
}

/**
 * Verify the input passed to `execute` is exactly the tool-call input recorded
 * in the approved message history (defense in depth against altered/replayed
 * arguments; the AI SDK HMAC signature is the first check).
 */
function toolCallInputMatchesReceived(
  messages: ModelMessage[],
  toolCallId: string,
  receivedInput: unknown,
): boolean {
  for (const message of messages) {
    if (!Array.isArray(message.content)) continue;
    for (const part of message.content as Array<{ type?: string }>) {
      if (part.type === 'tool-call' && (part as Record<string, unknown>).toolCallId === toolCallId) {
        return deepEqual((part as Record<string, unknown>).input, receivedInput);
      }
    }
  }
  return false;
}

/**
 * Wrap a tool's execute with the policy gate:
 * 1. a valid server execution context must exist and not be expired;
 * 2. approval-required tools must show an approved approval response for THIS
 *    tool call and the received input must be the exact approved input.
 * Read tools execute without approval but still refuse outside a valid context.
 */
export function gateToolExecution(
  policy: StoreManagerToolPolicy,
  context: StoreManagerToolContext,
  execute: AnyToolExecute,
): AnyToolExecute {
  return async (input, options) => {
    if (!context.executionId || context.executionId.length === 0 || !context.approvalExpiresAt) {
      throw new ApprovalGateError(
        'execution_context_missing',
        'Tool execution requires a server execution context; request was not routed through the Store Manager runtime.',
      );
    }
    if (Date.now() > context.approvalExpiresAt) {
      throw new ApprovalGateError(
        'approval_session_expired',
        'The approval session for this chat turn has expired. Re-send your message to continue.',
      );
    }

    if (policy.requiresApproval) {
      const messages = options?.messages ?? [];
      const state = approvalStateForToolCall(messages, options.toolCallId);
      if (state === 'approved') {
        if (!toolCallInputMatchesReceived(messages, options.toolCallId, input)) {
          throw new ApprovalGateError(
            'approval_replay_or_altered',
            `Tool call "${policy.name}" arguments were altered after approval; execution refused.`,
          );
        }
      } else if (state === 'denied') {
        throw new ApprovalGateError(
          'approval_denied',
          `Execution of "${policy.name}" was denied by the operator.`,
        );
      } else {
        // pending or missing: an approval-required tool was invoked without a
        // signed operator approval for this exact call — fail closed.
        throw new ApprovalGateError(
          'approval_missing',
          `Execution of "${policy.name}" requires explicit operator approval.`,
        );
      }
    }

    return execute(input, options);
  };
}

/**
 * Wrap every tool in `createStoreManagerTools` with its policy gate. Tools
 * without a policy registry entry fail loudly so a new unclassified tool can
 * never execute unguarded.
 */
function applyPolicyGate<T extends Record<string, any>>(
  tools: T,
  context: StoreManagerToolContext,
): T {
  const out = {} as Record<string, any>;
  for (const name of Object.keys(tools)) {
    const def = tools[name];
    const policy = requireStoreManagerToolPolicy(name);
    out[name] = {
      ...def,
      execute: gateToolExecution(policy, context, def.execute as AnyToolExecute),
    };
  }
  return out as T;
}

export function createStoreManagerTools(context: StoreManagerToolContext) {
  const { workspaceId, workspacePath } = context;

  const tools = {
    getDashboardStats: tool({
      description: 'Retrieve overall metrics and status for the store manager dashboard, including product counts, sync statuses, drift items, warnings, and recent activity.',
      inputSchema: z.object({}),
      execute: async () => {
        return getDashboardStatsData(workspaceId);
      },
    }),

    getCatalogHealthReport: tool({
      description: 'Retrieve the overall catalog health report summary, showing counts of healthy/unhealthy products, blockers, and warnings.',
      inputSchema: z.object({}),
      execute: async () => {
        const report = getCatalogHealthReport();
        return {
          totalProducts: report.totalProducts,
          healthyProducts: report.healthyProducts,
          unhealthyProducts: report.unhealthyProducts,
          totalErrors: report.totalErrors,
          totalWarnings: report.totalWarnings,
        };
      },
    }),

    listCatalogHealthIssues: tool({
      description: 'List detailed catalog health issues with optional filters for severity, code, field path, or a general search query.',
      inputSchema: z.object({
        severity: z.enum(['blocker', 'warning', 'info']).optional(),
        code: z.string().optional(),
        fieldPath: z.string().optional(),
        search: z.string().optional(),
        limit: z.number().int().min(1).max(100).default(25),
      }),
      execute: async ({ severity, code, fieldPath, search, limit }) => {
        const report = getCatalogHealthReport();
        let issues = report.issues;

        if (severity) {
          issues = issues.filter(i => i.severity === severity);
        }
        if (code) {
          issues = issues.filter(i => i.code === code);
        }
        if (fieldPath) {
          issues = issues.filter(i => i.fieldPath === fieldPath);
        }
        if (search) {
          const lower = search.toLowerCase();
          issues = issues.filter(i =>
            i.sku.toLowerCase().includes(lower) ||
            i.title.toLowerCase().includes(lower) ||
            (i.message && i.message.toLowerCase().includes(lower))
          );
        }

        return issues.slice(0, limit);
      },
    }),

    searchProducts: tool({
      description: 'Search the product index for active products matching a query or filter parameters.',
      inputSchema: z.object({
        search: z.string().optional(),
        status: z.string().optional(),
        inventoryStatus: z.string().optional(),
        minPrice: z.string().optional(),
        maxPrice: z.string().optional(),
        customFilters: z.record(z.string(), z.string()).optional(),
        limit: z.number().int().min(1).max(100).default(25),
      }),
      execute: async (filter) => {
        const result = listProductIndex(filter);
        return result.products;
      },
    }),

    getProductFieldAudit: tool({
      description: 'Scan active products and perform a detailed ProductField value audit, counting unique/missing values and detecting casing, whitespace, and separator duplicate groups.',
      inputSchema: z.object({
        field: z.string().describe('ProductField name, e.g. ProductField24 or ProductField16'),
        limit: z.number().int().min(1).max(500).default(100),
      }),
      execute: async ({ field, limit }) => {
        return getProductFieldAudit(field, limit);
      },
    }),

    proposeProductFieldNormalization: tool({
      description: 'Generate transient, in-memory proposals for a custom ProductField under a selected strategy. Read-only: does not save to the database.',
      inputSchema: z.object({
        field: z.string(),
        strategy: z.enum(['case_only', 'trim_whitespace', 'separator_cleanup', 'safe_duplicates']).default('safe_duplicates'),
        limit: z.number().int().min(1).max(500).default(100),
      }),
      execute: async ({ field, strategy, limit }) => {
        return proposeProductFieldNormalization(field, strategy, limit);
      },
    }),

    generateNormalizationProposals: tool({
      description: 'Generate and store normalization proposals in the database for a custom ProductField, making them ready to list and apply.',
      inputSchema: z.object({
        field: z.string().describe('ProductField name, e.g. ProductField24'),
      }),
      execute: async ({ field }) => {
        const proposals = generateDeterministicProposals(workspaceId, field);
        return { success: true, proposalCount: proposals.length };
      },
    }),

    listStoredProposals: tool({
      description: 'List stored normalization proposals from the database, with optional filters for field or status ("proposed", "applied", "dismissed").',
      inputSchema: z.object({
        field: z.string().optional(),
        status: z.enum(['proposed', 'applied', 'dismissed']).optional(),
      }),
      execute: async ({ field, status }) => {
        const proposals = listProposals(workspaceId, { field, status });
        return proposals;
      },
    }),

    applyNormalizationProposal: tool({
      description: 'Apply a stored proposal by its UUID, staging value updates for all affected products inside the active Change Set. The proposal must belong to the current workspace.',
      inputSchema: z.object({
        proposalId: z.string().describe('The UUID of the proposal to apply'),
      }),
      execute: async ({ proposalId }) => {
        try {
          const res = applyProposal(workspaceId, workspacePath, proposalId);
          return { success: true, changeSetId: res.changeSetId };
        } catch (err) {
          // Structured denial at the agent boundary: foreign/unknown ids never
          // disclose ownership and never reach the service side effects.
          return { success: false, error: err instanceof Error ? err.message : 'Failed to apply proposal.' };
        }
      },
    }),

    dismissNormalizationProposal: tool({
      description: 'Dismiss a stored proposal by its UUID so it will not be suggested or applied. The proposal must belong to the current workspace.',
      inputSchema: z.object({
        proposalId: z.string().describe('The UUID of the proposal to dismiss'),
      }),
      execute: async ({ proposalId }) => {
        try {
          dismissProposal(workspaceId, proposalId);
          return { success: true };
        } catch (err) {
          return { success: false, error: err instanceof Error ? err.message : 'Failed to dismiss proposal.' };
        }
      },
    }),

    explainNextActions: tool({
      description: 'Return a ranked list of recommended next actions based on current catalog health, drift status, and change sets.',
      inputSchema: z.object({
        focus: z.enum(['health', 'product_fields', 'sync', 'drift', 'onboarding']).optional(),
      }),
      execute: async () => {
        const report = getCatalogHealthReport();
        const stats = getDashboardStatsData(workspaceId);
        const actions: string[] = [];

        if (report.totalErrors > 0) {
          actions.push(`Fix the ${report.totalErrors} blocking errors in your catalog to enable remote sync.`);
        }
        if (stats.metrics.driftedProducts > 0) {
          actions.push(`Resolve the ${stats.metrics.driftedProducts} drifted products under Products -> Drift.`);
        }
        if (stats.metrics.productsWithWarnings > 0) {
          actions.push(`Review the ${stats.metrics.productsWithWarnings} warnings under Catalog Health.`);
        }
        if (stats.metrics.draftChangeSets > 0) {
          actions.push(`Review and approve the ${stats.metrics.draftChangeSets} active drafts in your Change Sets.`);
        }
        if (actions.length === 0) {
          actions.push('All catalog metrics look clean! You are ready to publish or run catalog exports.');
        }

        return { actions };
      },
    }),

    repairChangeSetImages: tool({
      description: 'Re-download product images for an approved change set from the original onboarding extraction data. Use when export images ZIP is empty because files were lost from disk. The change set must be approved and belong to the current workspace.',
      inputSchema: z.object({
        changeSetId: z.string().describe('The UUID of the change set to repair images for'),
      }),
      execute: async ({ changeSetId }) => {
        // Adapter only: all network/filesystem/SQL capability lives in the
        // hardened image-repair service so chat and the Change Set Review UI
        // route cannot drift or bypass the boundaries.
        const result = await repairChangeSetImagesForWorkspace({
          workspaceId,
          workspacePath,
          changeSetId,
        });
        if (result.status === 'not_found') {
          return { success: false, error: result.error };
        }
        if (result.status === 'policy_denied') {
          return { success: false, error: result.error, denial: 'policy_denied' as const };
        }
        if (result.status === 'error') {
          return { success: false, error: result.error };
        }
        return result.summary;
      },
    }),
  };

  // Wrap every tool with its policy gate (approval + execution context).
  return applyPolicyGate(tools, context);
}
