import React, { useEffect, useState } from 'react';
import { colors, fonts, rounded } from '../../theme';
import type { StoreManagerNotification } from '../../store-manager-api';
import { sortNotifications, unreadNotificationCount, formatInboxAge } from '../../store-manager-inbox-logic';
import type { EventStreamStatus } from '../../hooks/useStoreManagerEvents';

interface NotificationCenterProps {
  notifications: StoreManagerNotification[];
  status: EventStreamStatus;
  onMarkRead: (id: string) => void;
}

const SEVERITY_DOT: Record<string, string> = {
  critical: colors.signetBurgundy,
  warning: '#b08a2e',
  info: colors.seedlingGreen,
};

/**
 * NotificationCenter — deterministic in-app threshold facts (never model
 * prose). Rendered as a small dropdown; each item is template-generated by
 * the server rule engine and links to its Inbox item when present. Marking
 * read never resolves the underlying source finding.
 */
export function NotificationCenter({ notifications, status, onMarkRead }: NotificationCenterProps) {
  const [open, setOpen] = useState(false);
  const unread = unreadNotificationCount(notifications);
  const sorted = sortNotifications(notifications).slice(0, 40);

  // Close the popover after marking read when it becomes empty.
  useEffect(() => {
    if (open && notifications.length > 0 && unreadNotificationCount(notifications) === 0) {
      // keep open — the operator may still want to inspect history
    }
  }, [notifications, open]);

  return (
    <div style={{ position: 'relative', display: 'inline-block' }}>
      <button
        type="button"
        aria-label={`Notifications (${unread} unread)`}
        aria-expanded={open}
        onClick={() => setOpen((v) => !v)}
        className="btn btn-outline"
        style={{ height: '2rem', fontSize: '0.75rem', padding: '0 12px', position: 'relative' }}
      >
        🔔{unread > 0 ? <span style={{ marginLeft: 4, fontWeight: 800, color: colors.signetBurgundy }}>{unread}</span> : null}
      </button>
      {open ? (
        <div
          role="dialog"
          aria-label="Store Manager notifications"
          style={{
            position: 'absolute',
            right: 0,
            top: 40,
            zIndex: 60,
            width: 360,
            maxHeight: '60vh',
            overflowY: 'auto',
            background: colors.whiteSurface,
            border: `1px solid ${colors.cardBorder}`,
            borderRadius: rounded.md,
            boxShadow: '0 12px 32px rgba(0,0,0,0.16)',
            fontFamily: fonts.body,
            padding: 12,
          }}
        >
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 }}>
            <span style={{ fontSize: 13, fontWeight: 700, color: colors.ledgerCharcoal }}>
              Notifications {status === 'live' ? '· live' : status === 'reconnecting' ? '· reconnecting' : ''}
            </span>
            <button type="button" className="btn btn-outline" style={{ fontSize: 11, padding: '2px 8px' }} onClick={() => setOpen(false)}>
              Close
            </button>
          </div>
          {sorted.length === 0 ? (
            <div style={{ fontSize: 12, color: colors.mulchBrown }}>No notifications yet.</div>
          ) : (
            sorted.map((n) => (
              <div key={n.id} style={{ display: 'flex', gap: 8, padding: '8px 4px', borderBottom: `1px solid ${colors.cardBorder}` }}>
                <span
                  aria-hidden
                  style={{ width: 8, height: 8, borderRadius: '50%', marginTop: 5, background: SEVERITY_DOT[n.severity] ?? colors.mulchBrown, flexShrink: 0 }}
                />
                <div style={{ flex: 1 }}>
                  <div style={{ fontSize: 12, fontWeight: 700, color: colors.ledgerCharcoal }}>{n.title}</div>
                  <div style={{ fontSize: 11, color: colors.mulchBrown }}>{n.message}</div>
                  <div style={{ fontSize: 10, color: colors.mulchBrown, marginTop: 2 }}>
                    {formatInboxAge(n.createdAt)} · #{n.sequence}
                  </div>
                </div>
                {n.readAt === null ? (
                  <button
                    type="button"
                    className="btn btn-outline"
                    aria-label={`Mark notification read: ${n.title}`}
                    style={{ fontSize: 10, padding: '2px 6px', alignSelf: 'flex-start' }}
                    onClick={() => onMarkRead(n.id)}
                  >
                    Mark read
                  </button>
                ) : null}
              </div>
            ))
          )}
        </div>
      ) : null}
    </div>
  );
}
