/**
 * Human-ratified ShopSite page dispositions for bay-state-v4.
 *
 * These are projections only: nodeId must reference an existing v4 node and
 * this table never creates taxonomy leaves. Pages that are subsets, audience
 * views, or mixed-scope merchandising are explicitly merchandising rather
 * than being promoted to canonical leaves.
 */
export type RatifiedPageRole =
  | { role: 'canonical_leaf'; nodeId: string }
  | { role: 'merchandising' | 'shop_all_aggregate' | 'navigation'; nodeId: string | null };

export const PAGE_ROLE_RATIFICATIONS: Record<string, RatifiedPageRole> = {
  // Exact/high deterministic proposals, ratified after review.
  'Caged Bird Food': { role: 'merchandising', nodeId: null },
  'Cat Litter & Litter Boxes': { role: 'canonical_leaf', nodeId: 'cat-litter' },
  'Cat Toys & Scratchers': { role: 'canonical_leaf', nodeId: 'cat-toys' },
  'Dog Dental Treats': { role: 'merchandising', nodeId: 'dog-treats' },
  'Dog Treats Bakery': { role: 'merchandising', nodeId: 'dog-treats' },
  'Horse Treats': { role: 'merchandising', nodeId: 'horse-treats-supplements' },
  'Horse Vitamins & Supplements': { role: 'merchandising', nodeId: 'horse-treats-supplements' },
  'Wild Bird Seed & Seed Mixes': { role: 'canonical_leaf', nodeId: 'bird-food' },
  'Wildlife Deer Food': { role: 'canonical_leaf', nodeId: 'deer-wildlife-feed' },
  'Wood Pellets': { role: 'canonical_leaf', nodeId: 'heating-pellets-wood' },
  Boots: { role: 'canonical_leaf', nodeId: 'work-boots' },
  'Cat Food Dry': { role: 'canonical_leaf', nodeId: 'cat-food-dry' },
  'Cat Food Wet': { role: 'canonical_leaf', nodeId: 'cat-food-wet' },
  'Dog Crates & Carriers': { role: 'canonical_leaf', nodeId: 'dog-crates-kennels' },
  'Dog Food Dry': { role: 'canonical_leaf', nodeId: 'dog-food-dry' },
  'Dog Food Wet': { role: 'canonical_leaf', nodeId: 'dog-food-wet' },
  'Dog Treats Biscuits Cookies & Crunchy Treats': { role: 'merchandising', nodeId: 'dog-treats' },
  'Dog Treats Bones Bully Sticks & Natural Chews': { role: 'merchandising', nodeId: 'dog-treats' },
  'Dog Treats Soft & Chewy': { role: 'merchandising', nodeId: 'dog-treats' },
  Gloves: { role: 'canonical_leaf', nodeId: 'work-gloves' },
  Heating: { role: 'merchandising', nodeId: 'heating-fuel-climate-control' },
  'Wildlife Squirrel Food': { role: 'merchandising', nodeId: 'deer-wildlife-feed' },

  // Ambiguous species/family pages: retain the page as merchandising and
  // scope only when the existing hierarchy provides a safe parent.
  Apparel: { role: 'merchandising', nodeId: 'apparel-workwear' },
  'Barn Supplies Buckets & Feeders': { role: 'merchandising', nodeId: 'livestock-farm-animals' },
  'Barn Supplies Farm Gates & Fencing': { role: 'merchandising', nodeId: 'corral-panels-gates' },
  Beekeeping: { role: 'canonical_leaf', nodeId: 'bee-supplies' },
  'Caged Bird Canary & Finch': { role: 'merchandising', nodeId: null },
  'Caged Bird Cockatiel': { role: 'merchandising', nodeId: null },
  'Caged Bird Healthcare': { role: 'merchandising', nodeId: null },
  'Caged Bird Litter & Nesting': { role: 'merchandising', nodeId: null },
  'Caged Bird Parakeet': { role: 'merchandising', nodeId: null },
  'Caged Bird Parrot': { role: 'merchandising', nodeId: null },
  'Caged Bird Pigeon': { role: 'merchandising', nodeId: null },
  'Caged Bird Toys': { role: 'merchandising', nodeId: null },
  'Caged Bird Treats': { role: 'merchandising', nodeId: null },
  'Cat Beds & Carriers': { role: 'merchandising', nodeId: 'cat' },
  'Cat Bowls & Feeders': { role: 'merchandising', nodeId: 'cat' },
  'Cat Flea & Tick': { role: 'merchandising', nodeId: 'flea-tick-treatment' },
  'Cat Food Raw': { role: 'merchandising', nodeId: 'cat-food' },
  'Cat Grooming': { role: 'merchandising', nodeId: 'grooming' },
  'Cat Healthcare': { role: 'merchandising', nodeId: 'pet-health-wellness' },
  'Cat Leashes Collars & Harnesses': { role: 'merchandising', nodeId: 'collars-leashes' },
  'Dog Beds': { role: 'merchandising', nodeId: 'pet-beds' },
  'Dog Bowls & Feeders': { role: 'merchandising', nodeId: 'dog' },
  'Dog Cleanup': { role: 'merchandising', nodeId: 'dog' },
  'Dog Clothing & Accessories': { role: 'merchandising', nodeId: 'dog' },
  'Dog Flea & Tick': { role: 'merchandising', nodeId: 'flea-tick-treatment' },
  'Dog Food Raw': { role: 'merchandising', nodeId: 'dog-food' },
  'Dog Grooming': { role: 'merchandising', nodeId: 'grooming' },
  'Dog Healthcare': { role: 'merchandising', nodeId: 'pet-health-wellness' },
  'Dog Leashes Collars & Harnesses': { role: 'merchandising', nodeId: 'collars-leashes' },
  'Farm Animal Sheep & Goat': { role: 'merchandising', nodeId: 'goat-sheep-feed' },
  'Fencing & Gates': { role: 'merchandising', nodeId: 'corral-panels-gates' },
  'Fish Food Betta': { role: 'merchandising', nodeId: 'fish-food' },
  'Fish Food Goldfish': { role: 'merchandising', nodeId: 'fish-food' },
  'Fish Food Koi & Pond Fish': { role: 'merchandising', nodeId: 'fish-food' },
  'Fish Food Tropical': { role: 'merchandising', nodeId: 'fish-food' },
  'Gardening Tools & Supplies': { role: 'merchandising', nodeId: 'lawn-garden-landscaping' },
  'Horse Dewormers': { role: 'merchandising', nodeId: 'equine-horse-care' },
  'Horse First Aid': { role: 'merchandising', nodeId: 'equine-horse-care' },
  'Horse Fly Control': { role: 'canonical_leaf', nodeId: 'fly-control-equine' },
  'Horse Grooming': { role: 'canonical_leaf', nodeId: 'equine-grooming-hoof' },
  'Jerky Dog Treats': { role: 'merchandising', nodeId: 'dog-treats' },
  'Lawn Care': { role: 'merchandising', nodeId: 'lawn-garden-landscaping' },
  'Pest Control': { role: 'merchandising', nodeId: null },
  'Pest Control & Animal Repellents': { role: 'merchandising', nodeId: null },
  Plants: { role: 'merchandising', nodeId: 'lawn-garden-landscaping' },
  'Reptile Food & Treats': { role: 'merchandising', nodeId: null },
  'Seeds & Seed Starting': { role: 'merchandising', nodeId: 'lawn-garden-landscaping' },
  'Small Pet Bedding & Litter': { role: 'merchandising', nodeId: 'small-animal-feed-bedding' },
  'Small Pet Food': { role: 'merchandising', nodeId: 'small-animal-feed-bedding' },
  'Small Pet Grooming & Health': { role: 'merchandising', nodeId: 'pet-health-wellness' },
  'Small Pet Toys & Chews': { role: 'merchandising', nodeId: 'pet-supplies' },
  'Small Pet Treats': { role: 'merchandising', nodeId: 'pet-supplies' },
  'Wild Bird Baths': { role: 'merchandising', nodeId: 'bird-houses-baths' },
  'Wild Bird Hangers Poles & Baffles': { role: 'merchandising', nodeId: 'wild-bird-feeders' },
  'Wild Bird Houses': { role: 'canonical_leaf', nodeId: 'bird-houses-baths' },
  'Wild Bird Suet & Mealworms': { role: 'merchandising', nodeId: 'wild-bird' },

  // Unmatched pages: explicit merchandising dispositions; no taxonomy leaf is
  // invented for caged-bird, reptile, or species/audience-only pages.
  'Baby Chicks': { role: 'merchandising', nodeId: 'livestock-farm-animals' },
  'Barn Supplies Tools & Equipment': { role: 'merchandising', nodeId: 'livestock-farm-animals' },
  'Cage Bird Cages & Accessories': { role: 'merchandising', nodeId: null },
  'Farm Animal Chicken & Poultry': { role: 'merchandising', nodeId: 'livestock-farm-animals' },
  'Farm Animal Cow': { role: 'merchandising', nodeId: 'cattle-feed' },
  'Farm Animal Llama & Alpaca': { role: 'merchandising', nodeId: 'livestock-farm-animals' },
  'Farm Animal Pig': { role: 'merchandising', nodeId: 'pig-swine-feed' },
  'Fish Pond Supplies': { role: 'merchandising', nodeId: 'fish' },
  'Fish Tanks & Accessories': { role: 'merchandising', nodeId: 'fish' },
  'Fish Water Treatments & Test Kits': { role: 'merchandising', nodeId: 'fish' },
  'Flowers & Plants': { role: 'merchandising', nodeId: 'lawn-garden-landscaping' },
  Hay: { role: 'merchandising', nodeId: 'livestock-farm-animals' },
  'Mulch & Loam': { role: 'canonical_leaf', nodeId: 'potting-soil' },
  'Reptile Bearded Dragon': { role: 'merchandising', nodeId: null },
  'Reptile Bedding & Substrate': { role: 'merchandising', nodeId: null },
  'Reptile Frog': { role: 'merchandising', nodeId: null },
  'Reptile Heating & Lighting': { role: 'merchandising', nodeId: null },
  'Reptile Lizard': { role: 'merchandising', nodeId: null },
  'Reptile Snake': { role: 'merchandising', nodeId: null },
  'Reptile Tanks & Accessories': { role: 'merchandising', nodeId: null },
  'Reptile Turtle': { role: 'merchandising', nodeId: null },
  'Shavings & Bedding': { role: 'merchandising', nodeId: 'livestock-farm-animals' },
  'Small Pet Guinea Pig': { role: 'merchandising', nodeId: 'small-animal-feed-bedding' },
  'Small Pet Habitats & Accessories': { role: 'merchandising', nodeId: 'pet-supplies' },
  'Small Pet Hamster': { role: 'merchandising', nodeId: 'small-animal-feed-bedding' },
  'Small Pet Hay': { role: 'merchandising', nodeId: 'small-animal-feed-bedding' },
  'Small Pet Mouse & Rat': { role: 'merchandising', nodeId: 'small-animal-feed-bedding' },
  'Small Pet Rabbit': { role: 'merchandising', nodeId: 'small-animal-feed-bedding' },
};
